Repository argoproj-labs/hera, pull requests merged in 2023-09, with the labels that each got.

#755 Fix output Artifact/Parameter annotations
  CONTRIBUTING.md
  README.md
  docs/examples/workflows/script_annotations_outputs.md
  docs/getting-started/walk-through/advanced-hera-features.md
  examples/workflows/script-annotations-outputs.yaml
  examples/workflows/script_annotations_outputs.py
  src/hera/workflows/parameter.py
  src/hera/workflows/runner.py
  src/hera/workflows/script.py
  tests/__init__.py
  tests/script_annotations_outputs/script_annotations_output.py
  tests/script_annotations_outputs/script_annotations_output_custom_output_directory.py
  tests/test_runner.py
  tests/test_script_annotations.py
  tests/test_unit/test_script.py
Labels: semver:patch, type:bug

#758 Doc updates, rearrange rtd website, add user-guides and contributing tabs
  CONTRIBUTING.md
  README.md
  docs/examples/workflows-examples.md
  docs/user-guides/core-concepts.md
  docs/user-guides/expr.md
  examples/workflows-examples.md
  mkdocs.yml
  tests/test_remaining_examples.py
Labels: semver:patch, type:documentation

#759 Add getter for script kwargs func name
  src/hera/workflows/script.py
  tests/test_unit/test_script.py
Labels: semver:patch, type:bug

#752 Make service list APIs handle empty `items` case
  Makefile
  scripts/service.py
  scripts/spec.py
  src/hera/events/models/eventsource.py
  src/hera/events/models/google/__init__.py
  src/hera/events/models/google/protobuf.py
  src/hera/events/models/grpc/gateway/__init__.py
  src/hera/events/models/grpc/gateway/runtime.py
  src/hera/events/models/io/argoproj/events/__init__.py
  src/hera/events/models/io/argoproj/events/v1alpha1.py
  src/hera/events/models/io/argoproj/workflow/__init__.py
  src/hera/events/models/io/argoproj/workflow/v1alpha1.py
  src/hera/events/models/io/argoproj/workflow/v1alpha1.pyi
  src/hera/events/models/io/k8s/api/core/__init__.py
  src/hera/events/models/io/k8s/api/core/v1.py
  src/hera/events/models/io/k8s/api/policy/__init__.py
  src/hera/events/models/io/k8s/api/policy/v1beta1.py
  src/hera/events/models/io/k8s/apimachinery/pkg/api/__init__.py
  src/hera/events/models/io/k8s/apimachinery/pkg/api/resource.py
  src/hera/events/models/io/k8s/apimachinery/pkg/apis/meta/__init__.py
  src/hera/events/models/io/k8s/apimachinery/pkg/apis/meta/v1.py
  src/hera/events/models/io/k8s/apimachinery/pkg/util/__init__.py
  src/hera/events/models/io/k8s/apimachinery/pkg/util/intstr.py
  src/hera/events/models/sensor.py
  src/hera/workflows/models/eventsource.py
  src/hera/workflows/models/google/__init__.py
  src/hera/workflows/models/google/protobuf.py
  src/hera/workflows/models/grpc/gateway/__init__.py
  src/hera/workflows/models/grpc/gateway/runtime.py
  src/hera/workflows/models/io/argoproj/events/__init__.py
  src/hera/workflows/models/io/argoproj/events/v1alpha1.py
  src/hera/workflows/models/io/argoproj/workflow/__init__.py
  src/hera/workflows/models/io/argoproj/workflow/v1alpha1.py
  src/hera/workflows/models/io/argoproj/workflow/v1alpha1.pyi
  src/hera/workflows/models/io/k8s/api/core/__init__.py
  src/hera/workflows/models/io/k8s/api/core/v1.py
  src/hera/workflows/models/io/k8s/api/policy/__init__.py
  src/hera/workflows/models/io/k8s/api/policy/v1beta1.py
  src/hera/workflows/models/io/k8s/apimachinery/pkg/api/__init__.py
  src/hera/workflows/models/io/k8s/apimachinery/pkg/api/resource.py
  src/hera/workflows/models/io/k8s/apimachinery/pkg/apis/meta/__init__.py
  src/hera/workflows/models/io/k8s/apimachinery/pkg/apis/meta/v1.py
  src/hera/workflows/models/io/k8s/apimachinery/pkg/util/__init__.py
  src/hera/workflows/models/io/k8s/apimachinery/pkg/util/intstr.py
  src/hera/workflows/models/sensor.py
  src/hera/workflows/service.py
Labels: semver:patch, type:bug

#757 Add missing argument to NFSVolume build
  examples/workflows/volume-mounts-nfs.yaml
  examples/workflows/volume_mounts_nfs.py
  src/hera/workflows/volume.py
Labels: semver:patch, type:bug

#764 Add suspend template example where duration is configurable
  docs/examples/workflows/suspend_input_duration.md
  examples/workflows/suspend-input-duration.yaml
  examples/workflows/suspend_input_duration.py
Labels: semver:patch, type:documentation

#762 User guides
  CONTRIBUTING.md
  README.md
  docs/CONTRIBUTING.md
  docs/contributing/history.md
  docs/examples/workflows-examples.md
  docs/examples/workflows/upstream/k8s_set_owner_reference.md
  docs/examples/workflows/upstream/life_cycle_hooks_tmpl_level.md
  docs/examples/workflows/volume_mounts_nfs.md
  docs/examples/workflows/workflow_of_workflows.md
  docs/getting-started/introduction.md
  docs/getting-started/walk-through/advanced-hera-features.md
  docs/getting-started/walk-through/pydantic-support.md
  docs/user-guides/core-concepts.md
  docs/user-guides/expr.md
  docs/user-guides/scripts.md
  docs/walk-through/about-hera.md
  docs/walk-through/advanced-hera-features.md
  docs/walk-through/advanced-template-features.md
  docs/walk-through/advanced-workflow-features.md
  docs/walk-through/artifacts.md
  docs/walk-through/authentication.md
  docs/walk-through/conditionals.md
  docs/walk-through/dag.md
  docs/walk-through/hello-world.md
  docs/walk-through/loops.md
  docs/walk-through/parameters.md
  docs/walk-through/pydantic-support.md
  docs/walk-through/quick-start.md
  docs/walk-through/steps.md
  docs/walk-through/suspending.md
  examples/workflows/upstream/k8s-set-owner-reference.yaml
  examples/workflows/upstream/k8s_set_owner_reference.py
  examples/workflows/upstream/life-cycle-hooks-tmpl-level.yaml
  examples/workflows/upstream/life_cycle_hooks_tmpl_level.py
  examples/workflows/workflow-of-workflows.yaml
  examples/workflows/workflow_of_workflows.py
  mkdocs.yml
  src/hera/workflows/cron_workflow.py
  src/hera/workflows/script.py
  src/hera/workflows/workflow.py
  src/hera/workflows/workflow_template.py
Labels: semver:patch, type:documentation

#768 Fix indentation error for staticmethods decorated as scripts
  src/hera/workflows/script.py
  tests/test_unit/test_script.py
Labels: semver:patch, type:bug

#769 Fix link path and use stable
  README.md
Labels: semver:patch, type:documentation

#772 Fix errors with underscores in labels
  docs/examples/workflows/script_annotations_inputs.md
  docs/examples/workflows/script_annotations_outputs.md
  examples/workflows/script-annotations-inputs.yaml
  examples/workflows/script-annotations-outputs.yaml
  examples/workflows/script_annotations_inputs.py
  examples/workflows/script_annotations_outputs.py
  src/hera/workflows/script.py
  tests/script_annotations_artifacts/script_annotations_artifact_file.py
  tests/script_annotations_artifacts/script_annotations_artifact_file_with_path.py
  tests/script_annotations_artifacts/script_annotations_artifact_object.py
  tests/script_annotations_artifacts/script_annotations_artifact_path.py
  tests/script_annotations_artifacts/script_annotations_artifact_wrong_loader.py
  tests/script_annotations_inputs_regression/script_annotations_artifacts_artifactory_new.py
  tests/script_annotations_inputs_regression/script_annotations_artifacts_artifactory_old.py
  tests/script_annotations_inputs_regression/script_annotations_artifacts_azure_new.py
  tests/script_annotations_inputs_regression/script_annotations_artifacts_azure_old.py
  tests/script_annotations_inputs_regression/script_annotations_artifacts_gcs_new.py
  tests/script_annotations_inputs_regression/script_annotations_artifacts_gcs_old.py
  tests/script_annotations_inputs_regression/script_annotations_artifacts_git_new.py
  tests/script_annotations_inputs_regression/script_annotations_artifacts_git_old.py
  tests/script_annotations_inputs_regression/script_annotations_artifacts_hdfs_new.py
  tests/script_annotations_inputs_regression/script_annotations_artifacts_hdfs_old.py
  tests/script_annotations_inputs_regression/script_annotations_artifacts_http_new.py
  tests/script_annotations_inputs_regression/script_annotations_artifacts_http_old.py
  tests/script_annotations_inputs_regression/script_annotations_artifacts_mode_new.py
  tests/script_annotations_inputs_regression/script_annotations_artifacts_mode_old.py
  tests/script_annotations_inputs_regression/script_annotations_artifacts_mode_recurse_new.py
  tests/script_annotations_inputs_regression/script_annotations_artifacts_mode_recurse_old.py
  tests/script_annotations_inputs_regression/script_annotations_artifacts_optional_new.py
  tests/script_annotations_inputs_regression/script_annotations_artifacts_optional_old.py
  tests/script_annotations_inputs_regression/script_annotations_artifacts_oss_new.py
  tests/script_annotations_inputs_regression/script_annotations_artifacts_oss_old.py
  tests/script_annotations_inputs_regression/script_annotations_artifacts_raw_new.py
  tests/script_annotations_inputs_regression/script_annotations_artifacts_raw_old.py
  tests/script_annotations_inputs_regression/script_annotations_artifacts_s3_new.py
  tests/script_annotations_inputs_regression/script_annotations_artifacts_s3_old.py
  tests/script_annotations_inputs_regression/script_annotations_artifacts_subpath_new.py
  tests/script_annotations_inputs_regression/script_annotations_artifacts_subpath_old.py
  tests/script_annotations_inputs_regression/script_annotations_parameters_alias.py
  tests/script_annotations_inputs_regression/script_annotations_parameters_combined_new.py
  tests/script_annotations_inputs_regression/script_annotations_parameters_combined_old.py
  tests/script_annotations_inputs_regression/script_annotations_parameters_default_both.py
  tests/script_annotations_inputs_regression/script_annotations_parameters_default_new.py
  tests/script_annotations_inputs_regression/script_annotations_parameters_default_old.py
  tests/script_annotations_inputs_regression/script_annotations_parameters_description_new.py
  tests/script_annotations_inputs_regression/script_annotations_parameters_description_old.py
  tests/script_annotations_inputs_regression/script_annotations_parameters_enum_new.py
  tests/script_annotations_inputs_regression/script_annotations_parameters_enum_old.py
  tests/script_annotations_outputs/script_annotations_output.py
  tests/script_annotations_outputs/script_annotations_output_artifact_in_func.py
  tests/script_annotations_outputs/script_annotations_output_custom_output_directory.py
  tests/script_annotations_outputs/script_annotations_output_in_func_no_name.py
  tests/script_annotations_outputs/script_annotations_output_param_and_artifact_in_func.py
  tests/script_annotations_outputs/script_annotations_output_param_and_artifact_mix.py
  tests/script_annotations_outputs/script_annotations_output_param_in_func.py
  tests/test_runner.py
  tests/test_script_annotations.py
Labels: type:bug, semver:minor

#775 Use /tmp for all the autogenerated files
  src/hera/workflows/runner.py
  src/hera/workflows/script.py
  tests/script_annotations_outputs/script_annotations_output_multiple_calls.py
  tests/test_runner.py
  tests/test_script_annotations.py
Labels: semver:patch, type:bug

#782 Add k8s example to auth docs
  docs/walk-through/authentication.md
Labels: semver:patch, type:documentation

#780 Fixup volumes
  docs/examples/workflows/artifact.md
  docs/examples/workflows/artifact_with_fanout.md
  docs/examples/workflows/http.md
  docs/examples/workflows/script_annotations_artifact_custom_volume.md
  docs/examples/workflows/script_annotations_artifact_outputs_defaults.md
  docs/examples/workflows/script_annotations_artifact_passing.md
  docs/examples/workflows/script_annotations_outputs.md
  docs/examples/workflows/script_artifact_passing.md
  docs/examples/workflows/upstream/artifact_passing.md
  docs/examples/workflows/upstream/volumes_emptydir.md
  docs/examples/workflows/volume_mounts.md
  docs/examples/workflows/volume_mounts_wt.md
  examples/workflows/artifact-with-fanout.yaml
  examples/workflows/artifact.yaml
  examples/workflows/http.py
  examples/workflows/http.yaml
  examples/workflows/script-annotations-artifact-custom-volume.yaml
  examples/workflows/script-annotations-artifact-outputs-defaults.yaml
  examples/workflows/script-annotations-artifact-passing.yaml
  examples/workflows/script-annotations-outputs.yaml
  examples/workflows/script_annotations_artifact_custom_volume.py
  examples/workflows/script_annotations_artifact_outputs_defaults.py
  examples/workflows/script_annotations_artifact_passing.py
  examples/workflows/script_annotations_outputs.py
  examples/workflows/script_artifact_passing.py
  examples/workflows/upstream/artifact_passing.py
  examples/workflows/upstream/volumes_emptydir.py
  examples/workflows/volume_mounts.py
  examples/workflows/volume_mounts_wt.py
  src/hera/workflows/_mixins.py
  src/hera/workflows/runner.py
  src/hera/workflows/script.py
Labels: semver:patch, type:bug

#786 Fix script_annotations_artifact_passing example
  docs/examples/workflows/script_annotations_artifact_passing.md
  examples/workflows/script-annotations-artifact-passing.yaml
  examples/workflows/script_annotations_artifact_passing.py
Labels: semver:patch, type:documentation

#789 Fix outputs for empty strings
  src/hera/workflows/runner.py
  tests/script_annotations_outputs/script_annotations_output.py
  tests/test_runner.py
Labels: semver:patch, type:bug
