Repository argoproj-labs/hera, pull requests merged in 2023-01, with the labels that each got.

#381 Automate the release/changelog process
  .github/labels.yml
  .github/release-drafter.yml
  .github/workflows/cicd.yaml
  .github/workflows/minimal-labels.yml
  .github/workflows/publish.yml
  .github/workflows/release-updater.yml
  RELEASE.md
  pyproject.toml
  tests/test_version.py
Labels: enhancement, semver:patch, type:task

#399 pin Jinja2 to < 3.1
  docs/requirements.txt
Labels: semver:patch, type:skip-changelog, type:dependency-upgrade

#397 Setup notes k8s124up
  README.md
Labels: semver:patch, type:documentation

#398 Make verify SSL use `GlobalConfig` over service spec
  pyproject.toml
  src/hera/config.py
  src/hera/workflow_service.py
Labels: semver:patch, type:bug

#400 Add sync labels action
  .github/labels.yml
  .github/sync-labels.yml
  .github/workflows/cicd.yaml
Labels: semver:patch, type:skip-changelog

#401 Sync labels
  .github/sync-labels.yml
Labels: semver:patch, type:skip-changelog

#402 move syncer
  .github/workflows/sync-labels.yml
Labels: semver:patch, type:skip-changelog

#403 Adjust label colors
  .github/labels.yml
Labels: semver:patch, type:skip-changelog

#393 Fix name validation, add support for generate_name
  src/hera/validators.py
  src/hera/workflow.py
  tests/test_validators.py
Labels: semver:patch, type:task

#409 Task not properly parsing json containing multi-line strings
  src/hera/task.py
  tests/test_task.py
Labels: semver:patch, type:bug
