Repository argoproj-labs/hera, pull requests merged in 2023-05, with the labels that each got.

#620 Add sidecar examples and support for single user container specifications
  docs/examples/workflows/upstream/sidecar.md
  docs/examples/workflows/upstream/sidecar_dind.md
  docs/examples/workflows/upstream/sidecar_nginx.md
  examples/workflows/upstream/sidecar-dind.upstream.yaml
  examples/workflows/upstream/sidecar-dind.yaml
  examples/workflows/upstream/sidecar-nginx.upstream.yaml
  examples/workflows/upstream/sidecar-nginx.yaml
  examples/workflows/upstream/sidecar.py
  examples/workflows/upstream/sidecar.upstream.yaml
  examples/workflows/upstream/sidecar.yaml
  examples/workflows/upstream/sidecar_dind.py
  examples/workflows/upstream/sidecar_nginx.py
  src/hera/workflows/_mixins.py
  src/hera/workflows/container.py
  src/hera/workflows/container_set.py
  src/hera/workflows/dag.py
  src/hera/workflows/data.py
  src/hera/workflows/http_template.py
  src/hera/workflows/resource.py
  src/hera/workflows/script.py
  src/hera/workflows/steps.py
  src/hera/workflows/suspend.py
Labels: type:enhancement, semver:minor

#619 Add metrics from V4 and single sidecar support
  docs/examples/workflows/upstream/custom_metrics.md
  docs/examples/workflows/upstream/dag_custom_metrics.md
  docs/examples/workflows/upstream/sidecar.md
  docs/examples/workflows/upstream/sidecar_dind.md
  docs/examples/workflows/upstream/sidecar_nginx.md
  examples/workflows/upstream/custom-metrics.upstream.yaml
  examples/workflows/upstream/custom-metrics.yaml
  examples/workflows/upstream/custom_metrics.py
  examples/workflows/upstream/dag-custom-metrics.upstream.yaml
  examples/workflows/upstream/dag-custom-metrics.yaml
  examples/workflows/upstream/dag_custom_metrics.py
  examples/workflows/upstream/sidecar-dind.upstream.yaml
  examples/workflows/upstream/sidecar-dind.yaml
  examples/workflows/upstream/sidecar-nginx.upstream.yaml
  examples/workflows/upstream/sidecar-nginx.yaml
  examples/workflows/upstream/sidecar.py
  examples/workflows/upstream/sidecar.upstream.yaml
  examples/workflows/upstream/sidecar.yaml
  examples/workflows/upstream/sidecar_dind.py
  examples/workflows/upstream/sidecar_nginx.py
  src/hera/workflows/__init__.py
  src/hera/workflows/_mixins.py
  src/hera/workflows/container.py
  src/hera/workflows/container_set.py
  src/hera/workflows/dag.py
  src/hera/workflows/data.py
  src/hera/workflows/http_template.py
  src/hera/workflows/metrics.py
  src/hera/workflows/resource.py
  src/hera/workflows/script.py
  src/hera/workflows/steps.py
  src/hera/workflows/suspend.py
  src/hera/workflows/workflow.py
  src/hera/workflows/workflow_template.py
Labels: type:enhancement, semver:minor

#624 Fix get_parameter for Step
  src/hera/workflows/steps.py
Labels: semver:patch, type:bug

#626 Adding Intuition Machines to Users.md
  USERS.md
Labels: semver:patch, type:documentation

#629 Fix for volumes in WorkflowTemplate Spec
  docs/examples/workflows/volume_mounts_wt.md
  examples/workflows/volume-mounts-wt.yaml
  examples/workflows/volume_mounts_wt.py
  src/hera/workflows/workflow.py
  src/hera/workflows/workflow_template.py
Labels: semver:patch, type:bug

#632 Make `ContainerSet` full Hera object
  docs/examples/workflows/container_set_with_env.md
  examples/workflows/container-set-with-env.yaml
  examples/workflows/container_set_with_env.py
  src/hera/workflows/_mixins.py
  src/hera/workflows/container_set.py
Labels: semver:patch, type:bug

#634 Getting started docs
  docs/getting-started/introduction.md
  docs/getting-started/quick-start.md
  docs/getting-started/walk-through/about-hera.md
  docs/getting-started/walk-through/hello-world.md
  docs/hera_getting_started.md
  docs/introduction.md
  mkdocs.yml
Labels: semver:patch, type:documentation

#635 Fix types in script decorator
  src/hera/workflows/_mixins.py
  src/hera/workflows/script.py
Labels: type:enhancement, semver:minor

#640 [#603] Add host scheme validation
  examples/workflows/upstream/coinflip.upstream.yaml
  scripts/service.py
  src/hera/events/service.py
  src/hera/workflows/service.py
  tests/test_workflow.py
Labels: semver:patch, type:bug

#637 [#636] Add special case handling of cron workflow status
  scripts/service.py
  src/hera/workflows/service.py
Labels: semver:patch, type:bug

#644 Move properties/funcs into TISubNodeMixin
  src/hera/workflows/_mixins.py
  src/hera/workflows/steps.py
  src/hera/workflows/task.py
Labels: type:enhancement, semver:minor

#638 [#614] Add a Hera exceptions module
  scripts/service.py
  src/hera/events/service.py
  src/hera/exceptions/__init__.py
  src/hera/workflows/service.py
Labels: type:enhancement, semver:minor

#642 [#520] Add template apply
  src/hera/workflows/workflow_template.py
Labels: type:enhancement, semver:minor

#645 Add parameters walk through
  docs/getting-started/quick-start.md
  docs/getting-started/walk-through/parameters.md
  mkdocs.yml
Labels: semver:patch, type:documentation

#639 [#595] Improve artifact/parameter access
  src/hera/workflows/_mixins.py
  src/hera/workflows/steps.py
  src/hera/workflows/task.py
Labels: type:enhancement, semver:minor

#643 [#522] Add a wait + synchronous `Workflow.create`
  src/hera/workflows/cron_workflow.py
  src/hera/workflows/workflow.py
  src/hera/workflows/workflow_template.py
Labels: type:enhancement, semver:minor

#646 Parameters walkthrough typos
  docs/getting-started/walk-through/parameters.md
Labels: semver:patch, type:documentation

#648 Get any Artifacts/Parameters contained in function kwargs
  docs/examples/workflows/script_artifact_passing.md
  docs/getting-started/quick-start.md
  docs/getting-started/walk-through/hello-world.md
  docs/getting-started/walk-through/parameters.md
  examples/workflows/script-artifact-passing.yaml
  src/hera/workflows/_mixins.py
  src/hera/workflows/script.py
  tests/test_unit/test_script.py
Labels: semver:patch, type:bug

#647 [#513] Add source args inference to callable template mixin to support source kwargs in regular Py call
  README.md
  docs/examples/workflows/dag_diamond_with_callable_decorators.md
  docs/examples/workflows/script_artifact_passing.md
  docs/examples/workflows/script_variations.md
  docs/examples/workflows/script_with_default_params.md
  docs/examples/workflows/upstream/dag_diamond.md
  docs/examples/workflows/upstream/dag_nested.md
  docs/examples/workflows/upstream/loops.md
  docs/examples/workflows/upstream/loops_dag.md
  docs/examples/workflows/upstream/parallelism_nested_dag.md
  docs/getting-started/quick-start.md
  docs/getting-started/walk-through/hello-world.md
  docs/getting-started/walk-through/parameters.md
  examples/workflows/dag_diamond_with_callable_decorators.py
  examples/workflows/script_artifact_passing.py
  examples/workflows/script_variations.py
  examples/workflows/script_with_default_params.py
  examples/workflows/upstream/dag_diamond.py
  examples/workflows/upstream/dag_nested.py
  examples/workflows/upstream/loops.py
  examples/workflows/upstream/loops_dag.py
  examples/workflows/upstream/parallelism_nested_dag.py
  src/hera/workflows/_mixins.py
  src/hera/workflows/artifact.py
  src/hera/workflows/parameter.py
  src/hera/workflows/script.py
  tests/test_unit/test_script.py
Labels: type:enhancement, semver:minor

#658 Revert "[#513] Add source args inference to callable template mixin to support source kwargs in regular Py call"
  README.md
  docs/examples/workflows/daemon.md
  docs/examples/workflows/dag_diamond_with_callable_decorators.md
  docs/examples/workflows/default_param_overwrite.md
  docs/examples/workflows/dynamic_fanout_fanin.md
  docs/examples/workflows/map_reduce.md
  docs/examples/workflows/script_artifact_passing.md
  docs/examples/workflows/script_variations.md
  docs/examples/workflows/script_with_default_params.md
  docs/examples/workflows/upstream/dag_diamond.md
  docs/examples/workflows/upstream/dag_nested.md
  docs/examples/workflows/upstream/dag_targets.md
  docs/examples/workflows/upstream/loops.md
  docs/examples/workflows/upstream/loops_dag.md
  docs/examples/workflows/upstream/parallelism_nested_dag.md
  docs/examples/workflows/workflow_on_exit.md
  docs/getting-started/quick-start.md
  docs/getting-started/walk-through/hello-world.md
  docs/getting-started/walk-through/parameters.md
  examples/workflows/daemon.py
  examples/workflows/dag_diamond_with_callable_decorators.py
  examples/workflows/default_param_overwrite.py
  examples/workflows/dynamic_fanout_fanin.py
  examples/workflows/map_reduce.py
  examples/workflows/script_artifact_passing.py
  examples/workflows/script_variations.py
  examples/workflows/script_with_default_params.py
  examples/workflows/upstream/dag_diamond.py
  examples/workflows/upstream/dag_nested.py
  examples/workflows/upstream/dag_targets.py
  examples/workflows/upstream/loops.py
  examples/workflows/upstream/loops_dag.py
  examples/workflows/upstream/parallelism_nested_dag.py
  examples/workflows/workflow_on_exit.py
  src/hera/workflows/_mixins.py
  src/hera/workflows/artifact.py
  src/hera/workflows/parameter.py
  src/hera/workflows/script.py
  tests/test_unit/test_script.py
Labels: semver:patch, type:documentation

#657 Add Steps/DAG walk throughs
  docs/getting-started/walk-through/dag.md
  docs/getting-started/walk-through/hello-world.md
  docs/getting-started/walk-through/steps.md
  mkdocs.yml
  src/hera/workflows/task.py
Labels: semver:patch, type:documentation

#659 Artifacts walk through
  docs/examples/workflows/script_artifact_passing.md
  docs/getting-started/walk-through/artifacts.md
  examples/workflows/script-artifact-passing.yaml
  examples/workflows/script_artifact_passing.py
  mkdocs.yml
Labels: semver:patch, type:documentation

#662 Generate yamls only in python 3.8, roundtrip parse before comparing
  Makefile
  docs/examples/workflows/global_config.md
  docs/examples/workflows/map_reduce.md
  examples/workflows/global-config.yaml
  examples/workflows/global_config.py
  examples/workflows/map-reduce.yaml
  src/hera/workflows/_unparse.py
  tests/test_remaining_examples.py
  tests/test_workflow.py
Labels: semver:patch, type:bug
