Repository argoproj-labs/hera, pull requests merged in 2023-10, with the labels that each got.

#793 Selectively xfail upstream examples
  tests/test_remaining_examples.py
Labels: semver:patch, type:task

#794 Replace ruff excludes with pydocstyle ignores
  docs/examples/workflows/script_annotations_artifact_outputs_defaults.md
  docs/examples/workflows/script_annotations_artifact_passing.md
  docs/examples/workflows/script_annotations_inputs.md
  docs/examples/workflows/script_annotations_outputs.md
  docs/examples/workflows/upstream/volumes_emptydir.md
  docs/examples/workflows/volume_mounts_nfs.md
  examples/workflows/script_annotations_artifact_outputs_defaults.py
  examples/workflows/script_annotations_artifact_passing.py
  examples/workflows/script_annotations_inputs.py
  examples/workflows/script_annotations_outputs.py
  examples/workflows/upstream/volumes_emptydir.py
  examples/workflows/volume_mounts_nfs.py
  pyproject.toml
  src/hera/events/models/__init__.py
  src/hera/events/models/eventsource.py
  src/hera/events/models/eventsource.pyi
  src/hera/events/models/google/protobuf.pyi
  src/hera/events/models/grpc/gateway/runtime.pyi
  src/hera/events/models/io/argoproj/events/v1alpha1.py
  src/hera/events/models/io/argoproj/events/v1alpha1.pyi
  src/hera/events/models/io/argoproj/workflow/v1alpha1.py
  src/hera/events/models/io/argoproj/workflow/v1alpha1.pyi
  src/hera/events/models/io/k8s/api/core/v1.py
  src/hera/events/models/io/k8s/api/core/v1.pyi
  src/hera/events/models/io/k8s/api/policy/v1beta1.py
  src/hera/events/models/io/k8s/api/policy/v1beta1.pyi
  src/hera/events/models/io/k8s/apimachinery/pkg/api/resource.py
  src/hera/events/models/io/k8s/apimachinery/pkg/apis/meta/v1.py
  src/hera/events/models/io/k8s/apimachinery/pkg/apis/meta/v1.pyi
  src/hera/events/models/sensor.py
  src/hera/events/models/sensor.pyi
  src/hera/workflows/models/__init__.py
  src/hera/workflows/models/eventsource.py
  src/hera/workflows/models/eventsource.pyi
  src/hera/workflows/models/google/protobuf.pyi
  src/hera/workflows/models/grpc/gateway/runtime.pyi
  src/hera/workflows/models/io/argoproj/events/v1alpha1.py
  src/hera/workflows/models/io/argoproj/events/v1alpha1.pyi
  src/hera/workflows/models/io/argoproj/workflow/v1alpha1.py
  src/hera/workflows/models/io/argoproj/workflow/v1alpha1.pyi
  src/hera/workflows/models/io/k8s/api/core/v1.py
  src/hera/workflows/models/io/k8s/api/core/v1.pyi
  src/hera/workflows/models/io/k8s/api/policy/v1beta1.py
  src/hera/workflows/models/io/k8s/api/policy/v1beta1.pyi
  src/hera/workflows/models/io/k8s/apimachinery/pkg/api/resource.py
  src/hera/workflows/models/io/k8s/apimachinery/pkg/apis/meta/v1.py
  src/hera/workflows/models/io/k8s/apimachinery/pkg/apis/meta/v1.pyi
  src/hera/workflows/models/sensor.py
  src/hera/workflows/models/sensor.pyi
  tests/script_annotations_inputs_regression/script_annotations_configmap_old.py
  tests/test_remaining_examples.py
  tests/test_runner.py
  tests/test_script_annotations.py
  tests/test_unit/test_script.py
Labels: semver:patch, type:enhancement

#791 Fix subscripted generics for runner
  src/hera/workflows/runner.py
  tests/script_annotations_outputs/script_annotations_output.py
  tests/test_runner.py
Labels: semver:patch, type:bug

#801 Fix inherited_members
  mkdocs.yml
Labels: semver:patch, type:documentation

#798 Add missing build to mixin and QOL image pull policy builder
  src/hera/workflows/_mixins.py
  src/hera/workflows/user_container.py
  tests/test_unit/test_mixins.py
  tests/test_unit/test_user_container.py
Labels: semver:patch, type:bug

#806 Add ability to fetch workflow / cron workflow link
  scripts/service.py
  src/hera/workflows/cron_workflow.py
  src/hera/workflows/service.py
  src/hera/workflows/workflow.py
  tests/test_unit/test_cron_workflow.py
  tests/test_unit/test_workflow.py
Labels: type:enhancement, semver:minor

#805 Add example of how to run computation against a Dask cluster + Spark
  docs/examples/workflows/dask.md
  docs/examples/workflows/spark.md
  examples/workflows/dask.py
  examples/workflows/dask.yaml
  examples/workflows/spark.py
  examples/workflows/spark.yaml
  src/hera/workflows/workflow.py
  tests/test_unit/test_workflow.py
Labels: semver:patch, type:documentation

#811 Bug fixes for input Parameters and Artifacts in annotations
  docs/examples/workflows/callable_script.md
  examples/workflows/callable-script.yaml
  examples/workflows/callable_script.py
  src/hera/workflows/artifact.py
  src/hera/workflows/runner.py
  src/hera/workflows/script.py
  tests/conftest.py
  tests/helper.py
  tests/script_annotations/outputs.py
  tests/script_annotations_artifacts/script_annotations_artifact_file.py
  tests/script_annotations_artifacts/script_annotations_artifact_file_with_path.py
  tests/script_annotations_artifacts/script_annotations_artifact_object.py
  tests/script_annotations_artifacts/script_annotations_artifact_path.py
  tests/script_annotations_outputs/script_annotations_output_artifact_in_func.py
  tests/script_annotations_outputs/script_annotations_output_custom_output_directory.py
  tests/script_annotations_outputs/script_annotations_output_in_func_no_name.py
  tests/script_annotations_outputs/script_annotations_output_multiple_calls.py
  tests/script_annotations_outputs/script_annotations_output_param_and_artifact_in_func.py
  tests/script_annotations_outputs/script_annotations_output_param_and_artifact_mix.py
  tests/script_annotations_outputs/script_annotations_output_param_in_func.py
  tests/script_runner/annotated_outputs.py
  tests/script_runner/artifact_loaders.py
  tests/script_runner/artifact_with_invalid_loader.py
  tests/script_runner/parameter_inputs.py
  tests/script_runner/unknown_annotation_types.py
  tests/test_runner.py
  tests/test_script_annotations.py
  tests/test_unit/test_script.py
  tests/test_unit/test_workflow.py
Labels: semver:patch, type:bug

#815 Add optional kwarg to Artifact and upstream example
  docs/examples/workflows-examples.md
  docs/examples/workflows/upstream/ci_workflowtemplate.md
  examples/workflows/upstream/ci-workflowtemplate.yaml
  examples/workflows/upstream/ci_workflowtemplate.py
  src/hera/workflows/artifact.py
Labels: type:enhancement, semver:minor

#822 Use `cowsay` not `whalesay` as per official example
  docs/examples/workflows/workflow_of_workflows.md
  examples/workflows/workflow-of-workflows.yaml
  examples/workflows/workflow_of_workflows.py
Labels: semver:patch, type:documentation

#821 Add example for computing + using dynamic resources
  docs/examples/workflows/dynamic_resources.md
  examples/workflows/dynamic-resources.yaml
  examples/workflows/dynamic_resources.py
  src/hera/workflows/_mixins.py
Labels: semver:patch, type:documentation
