Repository argoproj-labs/hera, pull requests merged in 2023-03, with the labels that each got.

#449 Add DAG support to V5
  examples/v5/dag-coinflip.py
  src/hera/workflows/_base_model.py
  src/hera/workflows/v5/_context.py
  src/hera/workflows/v5/_mixins.py
  src/hera/workflows/v5/container.py
  src/hera/workflows/v5/dag.py
  src/hera/workflows/v5/protocol.py
  src/hera/workflows/v5/script.py
  src/hera/workflows/v5/tests/test_workflow.py
  src/hera/workflows/v5/workflow.py
Labels: type:enhancement, semver:major

#451 Add automated test-harness for examples and fix DAG tests
  .github/workflows/cicd.yaml
  examples/v5/dag-coinflip.py
  pyproject.toml
  src/hera/shared/global_config.py
  src/hera/workflows/v5/_context.py
  src/hera/workflows/v5/_mixins.py
  src/hera/workflows/v5/container.py
  src/hera/workflows/v5/dag.py
  src/hera/workflows/v5/examples/__init__.py
  src/hera/workflows/v5/examples/coinflip.py
  src/hera/workflows/v5/examples/coinflip.yaml
  src/hera/workflows/v5/examples/upstream/__init__.py
  src/hera/workflows/v5/examples/upstream/dag-conditional-parameters.yaml
  src/hera/workflows/v5/examples/upstream/dag-diamond.yaml
  src/hera/workflows/v5/examples/upstream/dag_conditional_parameters.py
  src/hera/workflows/v5/examples/upstream/dag_diamond.py
  src/hera/workflows/v5/examples/upstream/upstream.dag-conditional-parameters.yaml
  src/hera/workflows/v5/examples/upstream/upstream.dag-diamond.yaml
  src/hera/workflows/v5/protocol.py
  src/hera/workflows/v5/script.py
  src/hera/workflows/v5/task.py
  src/hera/workflows/v5/tests/test_workflow.py
  src/hera/workflows/v5/workflow.py
  src/hera/workflows/workflow_service.py
  tests/test_global_config.py
Labels: type:task, semver:major

#452 Add suspend
  src/hera/workflows/v5/container.py
  src/hera/workflows/v5/examples/suspend.py
  src/hera/workflows/v5/examples/suspend.yaml
  src/hera/workflows/v5/parameter.py
  src/hera/workflows/v5/suspend.py
Labels: type:enhancement, semver:major

#454 Add Data and HTTP templates
  .gitpod.yml
  src/hera/workflows/v5/_mixins.py
  src/hera/workflows/v5/data.py
  src/hera/workflows/v5/examples/data.py
  src/hera/workflows/v5/examples/data.yaml
  src/hera/workflows/v5/examples/http.py
  src/hera/workflows/v5/examples/http.yaml
  src/hera/workflows/v5/http.py
Labels: type:enhancement, semver:major

#456 Add Steps and ParallelSteps
  src/hera/workflows/v5/examples/steps-types.yaml
  src/hera/workflows/v5/examples/steps_types.py
  src/hera/workflows/v5/examples/upstream/steps.py
  src/hera/workflows/v5/examples/upstream/steps.yaml
  src/hera/workflows/v5/examples/upstream/upstream.steps.yaml
  src/hera/workflows/v5/protocol.py
  src/hera/workflows/v5/steps.py
Labels: type:enhancement, semver:major

#461 add resource, fix steps
  Makefile
  examples/workflows/k8s-resource-log-selector.yaml
  examples/workflows/k8s_resource_log_selector.py
  examples/workflows/resource-delete-with-flags.yaml
  examples/workflows/resource-flags.yaml
  examples/workflows/resource_delete_with_flags.py
  examples/workflows/resource_flags.py
  examples/workflows/upstream/dag_conditional_parameters.py
  src/hera/workflows/_mixins.py
  src/hera/workflows/resource.py
  src/hera/workflows/steps.py
Labels: type:enhancement, semver:major

#465 Add container set for V5
  docs/examples/workflows/graph_workflow.md
  docs/examples/workflows/k8s_resource_log_selector.md
  docs/examples/workflows/output_results_workflow.md
  docs/examples/workflows/parallel_workflow.md
  docs/examples/workflows/resource_delete_with_flags.md
  docs/examples/workflows/resource_flags.md
  docs/examples/workflows/sequence_workflow.md
  docs/examples/workflows/upstream/dag_conditional_parameters.md
  docs/examples/workflows/workspace_workflow.md
  examples/workflows/graph-workflow.yaml
  examples/workflows/graph_workflow.py
  examples/workflows/output-results-workflow.yaml
  examples/workflows/output_results_workflow.py
  examples/workflows/parallel-workflow.yaml
  examples/workflows/parallel_workflow.py
  examples/workflows/sequence-workflow.yaml
  examples/workflows/sequence_workflow.py
  examples/workflows/workspace-workflow.yaml
  examples/workflows/workspace_workflow.py
  src/hera/workflows/container_set.py
Labels: type:enhancement, semver:major

#464 Add a script to generate init files
  Makefile
  examples/workflows/coinflip.py
  examples/workflows/data.py
  examples/workflows/http.py
  examples/workflows/k8s_resource_log_selector.py
  examples/workflows/resource_delete_with_flags.py
  examples/workflows/resource_flags.py
  examples/workflows/steps_types.py
  examples/workflows/suspend.py
  examples/workflows/upstream/dag_conditional_parameters.py
  examples/workflows/upstream/dag_diamond.py
  examples/workflows/upstream/steps.py
  scripts/init_files.py
  src/hera/workflows/__init__.py
  src/hera/workflows/_base_model.py
  src/hera/workflows/container.py
  src/hera/workflows/dag.py
  src/hera/workflows/data.py
  src/hera/workflows/exceptions.py
  src/hera/workflows/http.py
  src/hera/workflows/resource.py
  src/hera/workflows/script.py
  src/hera/workflows/steps.py
  src/hera/workflows/suspend.py
  src/hera/workflows/task.py
  src/hera/workflows/task_result.py
  src/hera/workflows/user_container.py
  src/hera/workflows/workflow.py
  src/hera/workflows/workflow_status.py
Labels: type:task, semver:major

#466 Add fuzzy matchers for tests
  Makefile
  docs/examples/workflows/coinflip.md
  docs/examples/workflows/data.md
  docs/examples/workflows/http.md
  docs/examples/workflows/output_results_workflow.md
  docs/examples/workflows/parallel_workflow.md
  docs/examples/workflows/resource_flags.md
  docs/examples/workflows/steps_types.md
  docs/examples/workflows/suspend.md
  docs/examples/workflows/upstream/container_set_template__graph_workflow.md
  docs/examples/workflows/upstream/container_set_template__outputs_result_workflow.md
  docs/examples/workflows/upstream/container_set_template__parallel_workflow.md
  docs/examples/workflows/upstream/container_set_template__sequence_workflow.md
  docs/examples/workflows/upstream/container_set_template__workspace_workflow.md
  docs/examples/workflows/upstream/dag_conditional_parameters.md
  docs/examples/workflows/upstream/dag_diamond.md
  docs/examples/workflows/upstream/k8s_resource_log_selector.md
  docs/examples/workflows/upstream/resource_delete_with_flags.md
  docs/examples/workflows/upstream/steps.md
  docs/generate.py
  examples/workflows/output_results_workflow.py
  examples/workflows/parallel_workflow.py
  examples/workflows/sequence_workflow.py
  examples/workflows/upstream/container-set-template--graph-workflow.upstream.yaml
  examples/workflows/upstream/container-set-template--graph-workflow.yaml
  examples/workflows/upstream/container-set-template--outputs-result-workflow.upstream.yaml
  examples/workflows/upstream/container-set-template--outputs-result-workflow.yaml
  examples/workflows/upstream/container-set-template--parallel-workflow.upstream.yaml
  examples/workflows/upstream/container-set-template--parallel-workflow.yaml
  examples/workflows/upstream/container-set-template--sequence-workflow.upstream.yaml
  examples/workflows/upstream/container-set-template--sequence-workflow.yaml
  examples/workflows/upstream/container-set-template--workspace-workflow.upstream.yaml
  examples/workflows/upstream/container-set-template--workspace-workflow.yaml
  examples/workflows/upstream/container_set_template__graph_workflow.py
  examples/workflows/upstream/container_set_template__outputs_result_workflow.py
  examples/workflows/upstream/container_set_template__parallel_workflow.py
  examples/workflows/upstream/container_set_template__sequence_workflow.py
  examples/workflows/upstream/container_set_template__workspace_workflow.py
  examples/workflows/upstream/dag-conditional-parameters.yaml
  examples/workflows/upstream/dag-diamond.yaml
  examples/workflows/upstream/dag_conditional_parameters.py
  examples/workflows/upstream/dag_diamond.py
  examples/workflows/upstream/k8s-resource-log-selector.upstream.yaml
  examples/workflows/upstream/k8s-resource-log-selector.yaml
  examples/workflows/upstream/k8s_resource_log_selector.py
  examples/workflows/upstream/resource-delete-with-flags.upstream.yaml
  examples/workflows/upstream/resource-delete-with-flags.yaml
  examples/workflows/upstream/resource_delete_with_flags.py
  examples/workflows/upstream/steps.py
  examples/workflows/upstream/steps.yaml
  src/hera/workflows/__init__.py
  src/hera/workflows/container_set.py
  tests/test_workflow.py
Labels: type:documentation, semver:major

#475 Add WorkflowTemplate and CronWorkflow
  docs/examples/workflows/upstream/cron_workflow.md
  docs/examples/workflows/upstream/dag_inline_workflowtemplate.md
  examples/workflows/upstream/cron-workflow.upstream.yaml
  examples/workflows/upstream/cron-workflow.yaml
  examples/workflows/upstream/cron_workflow.py
  examples/workflows/upstream/dag-inline-workflowtemplate.upstream.yaml
  examples/workflows/upstream/dag-inline-workflowtemplate.yaml
  examples/workflows/upstream/dag_inline_workflowtemplate.py
  scripts/init_files.py
  src/hera/workflows/__init__.py
  src/hera/workflows/cron_workflow.py
  src/hera/workflows/protocol.py
  src/hera/workflows/task.py
  src/hera/workflows/workflow.py
  src/hera/workflows/workflow_template.py
  tests/test_workflow.py
Labels: type:enhancement, semver:major

#483 Add hooks for V5
  examples/workflows/upstream/conditional-artifacts.upstream.yaml
  src/hera/shared/global_config.py
  src/hera/workflows/__init__.py
  src/hera/workflows/container.py
  src/hera/workflows/container_set.py
  src/hera/workflows/cron_workflow.py
  src/hera/workflows/dag.py
  src/hera/workflows/exceptions.py
  src/hera/workflows/protocol.py
  src/hera/workflows/resource.py
  src/hera/workflows/script.py
  src/hera/workflows/steps.py
  src/hera/workflows/task.py
  src/hera/workflows/workflow.py
  src/hera/workflows/workflow_template.py
  tests/test_hooks.py
Labels: type:enhancement, semver:major

#482 Add PVC inference
  docs/examples/workflows/upstream/volumes_pvc.md
  examples/workflows/upstream/conditional-artifacts.upstream.yaml
  examples/workflows/upstream/volumes_pvc.py
  src/hera/shared/global_config.py
  src/hera/workflows/__init__.py
  src/hera/workflows/_mixins.py
  src/hera/workflows/container.py
  src/hera/workflows/container_set.py
  src/hera/workflows/cron_workflow.py
  src/hera/workflows/dag.py
  src/hera/workflows/exceptions.py
  src/hera/workflows/protocol.py
  src/hera/workflows/resource.py
  src/hera/workflows/script.py
  src/hera/workflows/steps.py
  src/hera/workflows/task.py
  src/hera/workflows/volume.py
  src/hera/workflows/workflow.py
  src/hera/workflows/workflow_template.py
  tests/test_hooks.py
Labels: type:enhancement, semver:major

#488 Rename hooks as `pre_build` and extend test
  src/hera/shared/global_config.py
  src/hera/workflows/container.py
  src/hera/workflows/container_set.py
  src/hera/workflows/cron_workflow.py
  src/hera/workflows/dag.py
  src/hera/workflows/resource.py
  src/hera/workflows/script.py
  src/hera/workflows/steps.py
  src/hera/workflows/task.py
  src/hera/workflows/workflow.py
  src/hera/workflows/workflow_template.py
  tests/test_hooks.py
Labels: type:enhancement, semver:minor

#490 Add `with_param` and `with_items` parameter inference + some upstream loop examples
  docs/examples/workflows/upstream/loops.md
  docs/examples/workflows/upstream/loops_dag.md
  docs/examples/workflows/upstream/loops_maps.md
  docs/examples/workflows/upstream/loops_param_result.md
  docs/examples/workflows/upstream/parallelism_limit.md
  docs/examples/workflows/upstream/parallelism_nested.md
  examples/workflows/upstream/loops-dag.upstream.yaml
  examples/workflows/upstream/loops-dag.yaml
  examples/workflows/upstream/loops-maps.upstream.yaml
  examples/workflows/upstream/loops-maps.yaml
  examples/workflows/upstream/loops-param-result.upstream.yaml
  examples/workflows/upstream/loops-param-result.yaml
  examples/workflows/upstream/loops.py
  examples/workflows/upstream/loops.upstream.yaml
  examples/workflows/upstream/loops.yaml
  examples/workflows/upstream/loops_dag.py
  examples/workflows/upstream/loops_maps.py
  examples/workflows/upstream/loops_param_result.py
  examples/workflows/upstream/parallelism-limit.upstream.yaml
  examples/workflows/upstream/parallelism-limit.yaml
  examples/workflows/upstream/parallelism-nested.upstream.yaml
  examples/workflows/upstream/parallelism-nested.yaml
  examples/workflows/upstream/parallelism_limit.py
  examples/workflows/upstream/parallelism_nested.py
  src/hera/workflows/_mixins.py
  src/hera/workflows/steps.py
Labels: type:enhancement, semver:minor

#489 Add decorators for pre-build hooks
  Makefile
  scripts/service.py
  src/hera/events/_base_model.py
  src/hera/events/models/eventsource.py
  src/hera/events/models/google/protobuf.py
  src/hera/events/models/grpc/gateway/runtime.py
  src/hera/events/models/io/argoproj/events/v1alpha1.py
  src/hera/events/models/io/argoproj/workflow/v1alpha1.py
  src/hera/events/models/io/k8s/api/core/v1.py
  src/hera/events/models/io/k8s/api/policy/v1beta1.py
  src/hera/events/models/io/k8s/apimachinery/pkg/api/resource.py
  src/hera/events/models/io/k8s/apimachinery/pkg/apis/meta/v1.py
  src/hera/events/models/io/k8s/apimachinery/pkg/util/intstr.py
  src/hera/events/models/sensor.py
  src/hera/events/service.py
  src/hera/shared/__init__.py
  src/hera/shared/_base_model.py
  src/hera/shared/_global_config.py
  src/hera/shared/global_config.py
  src/hera/workflows/_context.py
  src/hera/workflows/_mixins.py
  src/hera/workflows/archive.py
  src/hera/workflows/artifact.py
  src/hera/workflows/container.py
  src/hera/workflows/container_set.py
  src/hera/workflows/cron_workflow.py
  src/hera/workflows/dag.py
  src/hera/workflows/env.py
  src/hera/workflows/env_from.py
  src/hera/workflows/models/eventsource.py
  src/hera/workflows/models/google/protobuf.py
  src/hera/workflows/models/grpc/gateway/runtime.py
  src/hera/workflows/models/io/argoproj/events/v1alpha1.py
  src/hera/workflows/models/io/argoproj/workflow/v1alpha1.py
  src/hera/workflows/models/io/k8s/api/core/v1.py
  src/hera/workflows/models/io/k8s/api/policy/v1beta1.py
  src/hera/workflows/models/io/k8s/apimachinery/pkg/api/resource.py
  src/hera/workflows/models/io/k8s/apimachinery/pkg/apis/meta/v1.py
  src/hera/workflows/models/io/k8s/apimachinery/pkg/util/intstr.py
  src/hera/workflows/models/sensor.py
  src/hera/workflows/protocol.py
  src/hera/workflows/resource.py
  src/hera/workflows/resources.py
  src/hera/workflows/retry_strategy.py
  src/hera/workflows/script.py
  src/hera/workflows/service.py
  src/hera/workflows/steps.py
  src/hera/workflows/task.py
  src/hera/workflows/workflow.py
  src/hera/workflows/workflow_template.py
  tests/test_hooks.py
Labels: type:enhancement, semver:minor

#491 Add dynamic image setter
  src/hera/shared/_global_config.py
Labels: type:enhancement, semver:minor

#484 Support dynamic image lookup
  src/hera/global_config.py
  tests/test_global_config.py
Labels: type:enhancement, semver:minor

#494 Add a pre-release workflow
  .github/workflows/pre-release.yml
Labels: semver:patch, type:task

#495 Update README and examples
  README.md
  docs/examples/workflows/coinflip.md
  docs/examples/workflows/upstream/dag_diamond.md
  examples/workflows/coinflip.py
  examples/workflows/coinflip.yaml
  examples/workflows/upstream/dag_diamond.py
Labels: semver:patch, type:documentation

#497 Fix volume examples
  docs/examples/workflows/upstream/volumes-pvc.md
  docs/examples/workflows/upstream/volumes_existing.md
  docs/examples/workflows/upstream/volumes_pvc.md
  examples/workflows/upstream/volumes-pvc.py
  examples/workflows/upstream/volumes_existing.py
  examples/workflows/upstream/volumes_pvc.py
Labels: semver:patch, type:documentation

#496 Fix templateRef and clean up examples
  docs/examples/workflows/upstream/coinflip.md
  docs/examples/workflows/upstream/cron_workflow.md
  docs/examples/workflows/upstream/steps_inline_workflow.md
  docs/examples/workflows/upstream/workflow_template__dag.md
  docs/examples/workflows/upstream/workflow_template__hello_world.md
  docs/examples/workflows/upstream/workflow_template__workflow_template_ref.md
  examples/workflows/upstream/coinflip.py
  examples/workflows/upstream/coinflip.upstream.yaml
  examples/workflows/upstream/coinflip.yaml
  examples/workflows/upstream/cron-workflow.yaml
  examples/workflows/upstream/cron_workflow.py
  examples/workflows/upstream/steps-inline-workflow.upstream.yaml
  examples/workflows/upstream/steps-inline-workflow.yaml
  examples/workflows/upstream/steps_inline_workflow.py
  examples/workflows/upstream/workflow-template--dag.upstream.yaml
  examples/workflows/upstream/workflow-template--dag.yaml
  examples/workflows/upstream/workflow-template--hello-world.upstream.yaml
  examples/workflows/upstream/workflow-template--hello-world.yaml
  examples/workflows/upstream/workflow-template--workflow-template-ref.upstream.yaml
  examples/workflows/upstream/workflow-template--workflow-template-ref.yaml
  examples/workflows/upstream/workflow_template__dag.py
  examples/workflows/upstream/workflow_template__hello_world.py
  examples/workflows/upstream/workflow_template__workflow_template_ref.py
  src/hera/workflows/_mixins.py
  src/hera/workflows/env.py
  src/hera/workflows/steps.py
  src/hera/workflows/task.py
  tests/test_workflow.py
Labels: semver:patch, type:bug

#500 Add docs for v5
  docs/conf.py
  docs/examples/workflows/upstream/cluster_workflow_template__workflow_template_ref.md
  docs/examples/workflows/upstream/workflow_template__workflow_template_ref.md
  docs/hera_getting_started.md
  docs/index.rst
  docs/modules.rst
  docs/requirements.txt
  docs/src.rst
  examples/workflows/upstream/cluster-workflow-template--workflow-template-ref.upstream.yaml
  examples/workflows/upstream/cluster-workflow-template--workflow-template-ref.yaml
  examples/workflows/upstream/cluster_workflow_template__workflow_template_ref.py
  examples/workflows/upstream/workflow_template__workflow_template_ref.py
  scripts/init_files.py
  scripts/models.py
  src/hera/__init__.py
  src/hera/events/models/__init__.py
  src/hera/workflows/__init__.py
  src/hera/workflows/_mixins.py
  src/hera/workflows/artifact.py
  src/hera/workflows/container.py
  src/hera/workflows/cron_workflow.py
  src/hera/workflows/dag.py
  src/hera/workflows/models/__init__.py
  src/hera/workflows/parameter.py
  src/hera/workflows/script.py
  src/hera/workflows/steps.py
  src/hera/workflows/suspend.py
  src/hera/workflows/task.py
  src/hera/workflows/workflow.py
  src/hera/workflows/workflow_template.py
Labels: semver:patch, type:documentation

#505 Fix pydantic issues with hera.workflows.Env
  docs/examples/workflows/upstream/colored_logs.md
  examples/workflows/upstream/colored-logs.upstream.yaml
  examples/workflows/upstream/colored-logs.yaml
  examples/workflows/upstream/colored_logs.py
  src/hera/workflows/env.py
Labels: semver:patch, type:bug

#504 Add type-hints to ensure IDEs provide right auto-completion
  Makefile
  scripts/models.py
  src/hera/events/models/eventsource.pyi
  src/hera/events/models/google/protobuf.pyi
  src/hera/events/models/grpc/__init__.py
  src/hera/events/models/grpc/gateway/runtime.pyi
  src/hera/events/models/io/__init__.py
  src/hera/events/models/io/argoproj/__init__.py
  src/hera/events/models/io/argoproj/events/v1alpha1.pyi
  src/hera/events/models/io/argoproj/workflow/v1alpha1.pyi
  src/hera/events/models/io/k8s/__init__.py
  src/hera/events/models/io/k8s/api/__init__.py
  src/hera/events/models/io/k8s/api/core/v1.pyi
  src/hera/events/models/io/k8s/api/policy/v1beta1.pyi
  src/hera/events/models/io/k8s/apimachinery/__init__.py
  src/hera/events/models/io/k8s/apimachinery/pkg/__init__.py
  src/hera/events/models/io/k8s/apimachinery/pkg/api/resource.pyi
  src/hera/events/models/io/k8s/apimachinery/pkg/apis/__init__.py
  src/hera/events/models/io/k8s/apimachinery/pkg/apis/meta/v1.pyi
  src/hera/events/models/io/k8s/apimachinery/pkg/util/intstr.pyi
  src/hera/events/models/sensor.pyi
  src/hera/workflows/models/eventsource.pyi
  src/hera/workflows/models/google/protobuf.pyi
  src/hera/workflows/models/grpc/__init__.py
  src/hera/workflows/models/grpc/gateway/runtime.pyi
  src/hera/workflows/models/io/__init__.py
  src/hera/workflows/models/io/argoproj/__init__.py
  src/hera/workflows/models/io/argoproj/events/v1alpha1.pyi
  src/hera/workflows/models/io/argoproj/workflow/v1alpha1.pyi
  src/hera/workflows/models/io/k8s/__init__.py
  src/hera/workflows/models/io/k8s/api/__init__.py
  src/hera/workflows/models/io/k8s/api/core/v1.pyi
  src/hera/workflows/models/io/k8s/api/policy/v1beta1.pyi
  src/hera/workflows/models/io/k8s/apimachinery/__init__.py
  src/hera/workflows/models/io/k8s/apimachinery/pkg/__init__.py
  src/hera/workflows/models/io/k8s/apimachinery/pkg/api/resource.pyi
  src/hera/workflows/models/io/k8s/apimachinery/pkg/apis/__init__.py
  src/hera/workflows/models/io/k8s/apimachinery/pkg/apis/meta/v1.pyi
  src/hera/workflows/models/io/k8s/apimachinery/pkg/util/intstr.pyi
  src/hera/workflows/models/sensor.pyi
Labels: semver:patch, type:bug

#508 Switch to mkdocs for documentation
  .readthedocs.yaml
  README.md
  docs/CONTRIBUTING.md
  docs/Makefile
  docs/README.md
  docs/api/events/models.md
  docs/api/shared.md
  docs/api/workflows/hera.md
  docs/api/workflows/models.md
  docs/conf.py
  docs/index.rst
  docs/make.bat
  docs/requirements.txt
  docs/versions.json
  mkdocs.yml
  src/hera/shared/_global_config.py
Labels: semver:patch, type:documentation

#507 Add decorator for script
  README.md
  docs/examples/workflows/coinflip.md
  docs/examples/workflows/dag_conditional_parameters.md
  docs/examples/workflows/dag_diamond_with_callable_decorators.md
  docs/examples/workflows/http_.md
  docs/examples/workflows/upstream/coinflip.md
  docs/examples/workflows/upstream/colored_logs.md
  docs/examples/workflows/upstream/loops_param_result.md
  examples/workflows/coinflip.py
  examples/workflows/coinflip.yaml
  examples/workflows/dag-conditional-parameters.yaml
  examples/workflows/dag-diamond-with-callable-decorators.yaml
  examples/workflows/dag_conditional_parameters.py
  examples/workflows/dag_diamond_with_callable_decorators.py
  examples/workflows/http-.yaml
  examples/workflows/http_.py
  examples/workflows/upstream/coinflip.py
  examples/workflows/upstream/coinflip.yaml
  examples/workflows/upstream/colored_logs.py
  examples/workflows/upstream/loops-param-result.yaml
  examples/workflows/upstream/loops_param_result.py
  src/hera/workflows/__init__.py
  src/hera/workflows/_context.py
  src/hera/workflows/_mixins.py
  src/hera/workflows/container_set.py
  src/hera/workflows/dag.py
  src/hera/workflows/http_template.py
  src/hera/workflows/script.py
  src/hera/workflows/steps.py
  src/hera/workflows/workflow.py
Labels: type:enhancement, semver:minor

#514 Add PayIt to hera adopters
  USERS.md
Labels: semver:patch, type:documentation

#515 Fix env from
  docs/examples/workflows/env.md
  docs/examples/workflows/env_from.md
  examples/workflows/env-from.yaml
  examples/workflows/env.py
  examples/workflows/env.yaml
  examples/workflows/env_from.py
  src/hera/workflows/env_from.py
Labels: semver:patch, type:bug

#519 Add support for friendly env var definitions
  docs/examples/workflows/multi_env.md
  examples/workflows/multi-env.yaml
  examples/workflows/multi_env.py
  src/hera/workflows/_mixins.py
Labels: type:enhancement, semver:minor

#518 Add more syntactic sugar for complex condition setting
  docs/examples/workflows/complex_deps.md
  docs/examples/workflows/multi_env.md
  examples/workflows/complex-deps.yaml
  examples/workflows/complex_deps.py
  examples/workflows/multi-env.yaml
  examples/workflows/multi_env.py
  src/hera/workflows/_mixins.py
  src/hera/workflows/task.py
Labels: type:enhancement, semver:minor

#516 Publish to both `hera-workflows` and `hera` on PyPI
  .github/workflows/cicd.yaml
  .github/workflows/pre-release.yml
  .github/workflows/publish.yml
  CONTRIBUTING.md
  SECURITY.md
  docs/examples/workflows/env.md
  docs/examples/workflows/env_from.md
  docs/examples/workflows/upstream/image_pull_secrets.md
  docs/generate.py
  pyproject.toml
  src/hera/_version.py
Labels: type:enhancement, semver:minor

#526 Fix sed command filename
  .github/workflows/pre-release.yml
  .github/workflows/publish.yml
Labels: semver:patch, type:bug

#528 Fix token secret name for pre-release
  .github/workflows/pre-release.yml
Labels: semver:patch, type:bug

#517 Add ability to get task output parameters, more syntactic sugar around complex dependencies, and easier way to define env vars
  docs/examples/workflows/complex_deps.md
  docs/examples/workflows/dag_with_param_passing.md
  docs/examples/workflows/dag_with_script_param_passing.md
  docs/examples/workflows/multi_env.md
  docs/examples/workflows/script_with_default_params.md
  examples/workflows/complex-deps.yaml
  examples/workflows/complex_deps.py
  examples/workflows/dag-with-param-passing.yaml
  examples/workflows/dag-with-script-param-passing.yaml
  examples/workflows/dag_with_param_passing.py
  examples/workflows/dag_with_script_param_passing.py
  examples/workflows/multi-env.yaml
  examples/workflows/multi_env.py
  examples/workflows/script-with-default-params.yaml
  examples/workflows/script_with_default_params.py
  src/hera/shared/serialization.py
  src/hera/workflows/_mixins.py
  src/hera/workflows/parameter.py
  src/hera/workflows/script.py
  src/hera/workflows/steps.py
  src/hera/workflows/task.py
Labels: type:enhancement, semver:minor

#529 Adjust dynamic volume provisioning
  docs/examples/workflows/dynamic_volumes.md
  docs/examples/workflows/upstream/colored_logs.md
  docs/examples/workflows/upstream/volumes_pvc.md
  docs/examples/workflows/volume_mounts.md
  examples/workflows/dynamic-volumes.yaml
  examples/workflows/dynamic_volumes.py
  examples/workflows/upstream/colored_logs.py
  examples/workflows/upstream/volumes_pvc.py
  examples/workflows/volume-mounts.yaml
  examples/workflows/volume_mounts.py
  src/hera/workflows/_mixins.py
  src/hera/workflows/volume.py
  src/hera/workflows/workflow.py
Labels: semver:patch, type:enhancement

#530 Rename hera-workflows to hera
  CHANGELOG.md
  README.md
  RELEASE.md
  SECURITY.md
  docs/overrides/main.html
  mkdocs.yml
  pyproject.toml
Labels: type:documentation, semver:major

#531 Add a simple utility to save workflow to a file
  src/hera/workflows/workflow.py
  tests/test_workflow.py
Labels: type:enhancement, semver:minor

#534 Create CODEOWNERS
  .github/CODEOWNERS
Labels: semver:patch, type:skip-changelog

#533 Create MAINTAINERS.md
  MAINTAINERS.md
Labels: semver:patch, type:skip-changelog

#535 Add maintainers to pyproject.toml
  pyproject.toml
Labels: semver:patch, type:documentation

#537 Fix ineffective GlobalConfig Workflow settings
  docs/examples/workflows/global_config.md
  examples/workflows/global-config.yaml
  examples/workflows/global_config.py
  src/hera/workflows/workflow.py
  tests/test_workflow.py
Labels: semver:patch, type:bug
