Repository argoproj-labs/hera, pull requests merged in 2023-07, with the labels that each got.

#701 Add Content-Type header to PUT and POST requests
  scripts/service.py
  src/hera/events/service.py
  src/hera/workflows/service.py
Labels: semver:patch, type:enhancement

#710 Fix: script function called under workflow no longer returns a Step
  docs/examples/workflows/hello_world.md
  examples/workflows/hello-world.yaml
  examples/workflows/hello_world.py
  src/hera/workflows/_mixins.py
  tests/test_context.py
  tests/test_unit/test_container_set.py
  tests/test_unit/test_workflow.py
Labels: semver:patch, type:bug

#715 Make steps callable, add dag/steps callable examples
  docs/examples/workflows/callable_dag.md
  docs/examples/workflows/callable_steps.md
  examples/workflows/callable-dag.yaml
  examples/workflows/callable-steps.yaml
  examples/workflows/callable_dag.py
  examples/workflows/callable_steps.py
  src/hera/workflows/dag.py
  src/hera/workflows/steps.py
Labels: type:enhancement, semver:minor

#719 Fix artifact example
  docs/examples/workflows/artifact.md
  examples/workflows/artifact.py
  examples/workflows/artifact.yaml
Labels: semver:patch, type:documentation

#708 Script annotations for input Parameters
  docs/examples/workflows/callable_script.md
  docs/examples/workflows/script_annotations_alias.md
  docs/examples/workflows/script_annotations_combined_new.md
  docs/examples/workflows/script_annotations_combined_old.md
  docs/examples/workflows/script_annotations_default_both.md
  docs/examples/workflows/script_annotations_default_new.md
  docs/examples/workflows/script_annotations_default_old.md
  docs/examples/workflows/script_annotations_description_new.md
  docs/examples/workflows/script_annotations_description_old.md
  docs/examples/workflows/script_annotations_enum_new.md
  docs/examples/workflows/script_annotations_enum_old.md
  docs/getting-started/walk-through/advanced-hera-features.md
  examples/workflows/callable-script.yaml
  examples/workflows/callable_script.py
  examples/workflows/script-annotations-alias.yaml
  examples/workflows/script-annotations-combined-new.yaml
  examples/workflows/script-annotations-combined-old.yaml
  examples/workflows/script-annotations-default-both.yaml
  examples/workflows/script-annotations-default-new.yaml
  examples/workflows/script-annotations-default-old.yaml
  examples/workflows/script-annotations-description-new.yaml
  examples/workflows/script-annotations-description-old.yaml
  examples/workflows/script-annotations-enum-new.yaml
  examples/workflows/script-annotations-enum-old.yaml
  examples/workflows/script_annotations_alias.py
  examples/workflows/script_annotations_combined_new.py
  examples/workflows/script_annotations_combined_old.py
  examples/workflows/script_annotations_default_both.py
  examples/workflows/script_annotations_default_new.py
  examples/workflows/script_annotations_default_old.py
  examples/workflows/script_annotations_description_new.py
  examples/workflows/script_annotations_description_old.py
  examples/workflows/script_annotations_enum_new.py
  examples/workflows/script_annotations_enum_old.py
  src/hera/workflows/parameter.py
  src/hera/workflows/runner.py
  src/hera/workflows/script.py
  tests/test_runner.py
  tests/test_script_annotations.py
  tests/test_unit/test_parameter.py
Labels: type:enhancement, semver:minor

#723 Add global_config_fixture, fix broken tests
  tests/conftest.py
  tests/test_examples.py
  tests/test_script_annotations.py
  tests/test_unit/test_hooks.py
  tests/test_unit/test_workflow_template.py
Labels: type:skip-changelog

#729 Tolerate potential race condition in workflow create + wait
  src/hera/workflows/workflow.py
Labels: semver:patch, type:bug
