Repository argoproj-labs/hera, pull requests merged in 2023-06, with the labels that each got.

#661 Common arg inference code for steps/tasks
  docs/examples/workflows/script_loops_maps.md
  examples/workflows/script-loops-maps.yaml
  examples/workflows/script_loops_maps.py
  src/hera/workflows/_mixins.py
Labels: semver:patch, type:enhancement

#660 Add loops walkthrough (with_item/with_param, fanout/fanin)
  docs/getting-started/walk-through/loops.md
  mkdocs.yml
Labels: semver:patch, type:documentation

#663 Add pypi-prod env for publish workflow
  .github/workflows/minimal-labels.yml
  .github/workflows/publish.yml
  RELEASE.md
Labels: type:skip-changelog

#667 Add Quick Start link to README
  README.md
Labels: type:skip-changelog

#655 Add an `auth` module that can help users generate tokens
  docs/getting-started/walk-through/authentication.md
  mkdocs.yml
  src/hera/auth/__init__.py
  src/hera/shared/_global_config.py
  src/hera/workflows/workflow.py
Labels: type:enhancement, semver:minor

#669 WorkflowTemplate/ClusterWorkflowTemplate create_as_workflow
  Makefile
  src/hera/workflows/cluster_workflow_template.py
  src/hera/workflows/protocol.py
  src/hera/workflows/workflow.py
  src/hera/workflows/workflow_template.py
  tests/test_examples.py
  tests/test_unit/test_cluster_workflow_template.py
  tests/test_unit/test_hooks.py
  tests/test_unit/test_workflow.py
  tests/test_unit/test_workflow_template.py
Labels: type:enhancement, semver:minor

#683 Update workflow.py
  src/hera/workflows/workflow.py
Labels: semver:patch, type:documentation

#681 Add CronWorkflow.update, add unit tests
  src/hera/workflows/cron_workflow.py
  tests/test_unit/test_cron_workflow.py
Labels: semver:patch, type:enhancement

#685 Minor fix to CronWorkflow update
  src/hera/workflows/cron_workflow.py
  tests/test_unit/test_cron_workflow.py
Labels: semver:patch, type:bug

#684 Doc fixes
  docs/examples/workflows-examples.md
  docs/examples/workflows/dag_with_script_output_param_passing.md
  docs/examples/workflows/upstream/coinflip_recursive.md
  docs/examples/workflows/upstream/suspend_template.md
  docs/examples/workflows/upstream/suspend_template_outputs.md
  docs/examples/workflows/workflow_of_workflows.md
  docs/getting-started/walk-through/about-hera.md
  examples/workflows/dag_with_script_output_param_passing.py
  examples/workflows/upstream/coinflip_recursive.py
  examples/workflows/upstream/suspend_template.py
  examples/workflows/upstream/suspend_template_outputs.py
  examples/workflows/workflow_of_workflows.py
  mkdocs.yml
Labels: semver:patch, type:documentation

#686 Set status=None if any status field is None
  scripts/service.py
  src/hera/workflows/service.py
Labels: semver:patch, type:bug

#673 Move to Annotated for mapping hera to models. Add from/to functions
  codecov.yml
  docs/getting-started/walk-through/advanced-hera-features.md
  src/hera/workflows/_inspect.py
  src/hera/workflows/_mixins.py
  src/hera/workflows/cron_workflow.py
  src/hera/workflows/workflow.py
  src/hera/workflows/workflow_template.py
  tests/test_examples.py
  tests/test_unit/test_workflow.py
Labels: type:enhancement, semver:minor

#689 [#687] Adjust image pull policy guessing engine
  src/hera/workflows/_mixins.py
  src/hera/workflows/script.py
Labels: semver:patch, type:bug

#691 Add loops_arbitrary_sequential_steps example
  docs/examples/workflows/upstream/loops_arbitrary_sequential_steps.md
  docs/getting-started/walk-through/loops.md
  examples/workflows/upstream/loops-arbitrary-sequential-steps.upstream.yaml
  examples/workflows/upstream/loops-arbitrary-sequential-steps.yaml
  examples/workflows/upstream/loops_arbitrary_sequential_steps.py
Labels: semver:patch, type:documentation

#693 Fix create_as_workflow and improve test
  docs/getting-started/walk-through/advanced-hera-features.md
  src/hera/workflows/workflow_template.py
  tests/test_unit/test_workflow_template.py
Labels: semver:patch, type:bug

#698 Fix the artifact fanout example
  docs/examples/workflows/artifact_with_fanout.md
  examples/workflows/artifact-with-fanout.yaml
  examples/workflows/artifact_with_fanout.py
Labels: semver:patch, type:documentation

#696 Add more documentation
  README.md
  mkdocs.yml
  scripts/service.py
  src/hera/auth/__init__.py
  src/hera/events/service.py
  src/hera/exceptions/__init__.py
  src/hera/shared/__init__.py
  src/hera/shared/_base_model.py
  src/hera/shared/_global_config.py
  src/hera/shared/serialization.py
  src/hera/workflows/_context.py
  src/hera/workflows/_mixins.py
  src/hera/workflows/archive.py
  src/hera/workflows/artifact.py
  src/hera/workflows/container.py
  src/hera/workflows/container_set.py
  src/hera/workflows/dag.py
  src/hera/workflows/data.py
  src/hera/workflows/env.py
  src/hera/workflows/http_template.py
  src/hera/workflows/operator.py
  src/hera/workflows/protocol.py
  src/hera/workflows/resources.py
  src/hera/workflows/retry_strategy.py
  src/hera/workflows/runner.py
  src/hera/workflows/script.py
  src/hera/workflows/service.py
  src/hera/workflows/steps.py
  src/hera/workflows/suspend.py
  src/hera/workflows/user_container.py
  src/hera/workflows/workflow.py
  src/hera/workflows/workflow_template.py
Labels: semver:patch, type:documentation
