Repository argoproj-labs/hera, pull requests merged in 2023-11, with the labels that each got.

#824 Add dag note about dependency declaration
  docs/walk-through/dag.md
Labels: semver:patch, type:documentation

#826 Add `dependabot.yml`
  .github/dependabot.yml
Labels: semver:patch, type:task

#836 Clarify DAG walkthrough
  docs/walk-through/dag.md
Labels: semver:patch, type:documentation

#820 Add Pydantic `Extra.forbid` to shared base model config
  docs/examples/workflows-examples.md
  docs/examples/workflows/volume_mounts_nfs.md
  docs/examples/workflows/webhdfs_input_output_artifacts.md
  examples/workflows/volume_mounts_nfs.py
  examples/workflows/webhdfs-input-output-artifacts.yaml
  examples/workflows/webhdfs_input_output_artifacts.py
  src/hera/shared/_base_model.py
  src/hera/workflows/_mixins.py
  src/hera/workflows/artifact.py
  src/hera/workflows/user_container.py
  tests/script_annotations_inputs_regression/script_annotations_artifacts_mode_recurse_new.py
  tests/script_annotations_inputs_regression/script_annotations_artifacts_mode_recurse_old.py
  tests/script_annotations_inputs_regression/script_annotations_artifacts_oss_new.py
  tests/script_annotations_inputs_regression/script_annotations_artifacts_oss_old.py
  tests/script_annotations_inputs_regression/script_annotations_artifacts_s3_new.py
  tests/script_annotations_inputs_regression/script_annotations_artifacts_s3_old.py
  tests/script_annotations_inputs_regression/script_annotations_artifacts_sub_path_new.py
  tests/script_annotations_inputs_regression/script_annotations_artifacts_sub_path_old.py
  tests/script_annotations_inputs_regression/script_annotations_configmap_new.py
  tests/script_annotations_inputs_regression/script_annotations_configmap_old.py
  tests/test_script_annotations.py
  tests/test_unit/test_user_container.py
Labels: type:enhancement, semver:minor

#839 Remove black as formatter
  CONTRIBUTING.md
  Makefile
  docs/examples/workflows/script_annotations_artifact_custom_volume.md
  docs/examples/workflows/script_annotations_artifact_outputs_defaults.md
  docs/examples/workflows/script_annotations_artifact_passing.md
  docs/examples/workflows/upstream/container_set_template__workspace_workflow.md
  docs/examples/workflows/workflow_of_workflows.md
  examples/workflows/script_annotations_artifact_custom_volume.py
  examples/workflows/script_annotations_artifact_outputs_defaults.py
  examples/workflows/script_annotations_artifact_passing.py
  examples/workflows/upstream/container_set_template__workspace_workflow.py
  examples/workflows/upstream/webhdfs-input-output-artifacts.yaml
  examples/workflows/workflow-of-workflows.yaml
  poetry.lock
  pyproject.toml
  src/hera/events/models/eventsource.py
  src/hera/events/models/io/argoproj/events/v1alpha1.py
  src/hera/events/models/io/argoproj/workflow/v1alpha1.py
  src/hera/events/models/io/k8s/api/core/v1.py
  src/hera/events/models/io/k8s/api/policy/v1beta1.py
  src/hera/events/models/io/k8s/apimachinery/pkg/api/resource.py
  src/hera/events/models/io/k8s/apimachinery/pkg/apis/meta/v1.py
  src/hera/workflows/_mixins.py
  src/hera/workflows/models/eventsource.py
  src/hera/workflows/models/io/argoproj/events/v1alpha1.py
  src/hera/workflows/models/io/argoproj/workflow/v1alpha1.py
  src/hera/workflows/models/io/k8s/api/core/v1.py
  src/hera/workflows/models/io/k8s/api/policy/v1beta1.py
  src/hera/workflows/models/io/k8s/apimachinery/pkg/api/resource.py
  src/hera/workflows/models/io/k8s/apimachinery/pkg/apis/meta/v1.py
  src/hera/workflows/script.py
  tests/script_annotations/outputs.py
  tests/script_annotations_inputs_regression/script_annotations_artifacts_artifactory_new.py
  tests/script_annotations_inputs_regression/script_annotations_artifacts_azure_new.py
  tests/script_annotations_inputs_regression/script_annotations_artifacts_gcs_new.py
  tests/script_annotations_inputs_regression/script_annotations_artifacts_git_new.py
  tests/script_annotations_inputs_regression/script_annotations_artifacts_hdfs_new.py
  tests/script_annotations_inputs_regression/script_annotations_artifacts_http_new.py
  tests/script_annotations_inputs_regression/script_annotations_artifacts_oss_new.py
  tests/script_annotations_inputs_regression/script_annotations_artifacts_raw_new.py
  tests/script_annotations_inputs_regression/script_annotations_artifacts_s3_new.py
  tests/script_annotations_inputs_regression/script_annotations_configmap_new.py
Labels: semver:patch, type:task

#842 Update bug report template
  .github/ISSUE_TEMPLATE/🐛-bug-report.md
Labels: type:skip-changelog

#848 Fix docs/CONTRIBUTING.md to be symlink
  docs/CONTRIBUTING.md
Labels: type:skip-changelog

#851 Update README.md with example repo from KubeCon
  README.md
Labels: semver:patch, type:documentation

#852 Update README.md with YouTube link to talk
  README.md
Labels: semver:patch, type:documentation

#853 Fix indent
  README.md
Labels: type:skip-changelog

#857 Fix enum bool serialization and add tests for all serialized values
  src/hera/workflows/parameter.py
  tests/test_unit/test_parameter.py
Labels: type:bug, semver:minor

#856 Fix annotation directories
  docs/examples/workflows/script_annotations_artifact_custom_volume.md
  docs/examples/workflows/script_annotations_artifact_loaders.md
  docs/examples/workflows/script_annotations_artifact_outputs_defaults.md
  docs/examples/workflows/script_annotations_artifact_passing.md
  docs/examples/workflows/script_annotations_inputs.md
  examples/workflows/script-annotations-artifact-custom-volume.yaml
  examples/workflows/script-annotations-artifact-loaders.yaml
  examples/workflows/script-annotations-artifact-outputs-defaults.yaml
  examples/workflows/script-annotations-artifact-passing.yaml
  examples/workflows/script-annotations-inputs.yaml
  src/hera/workflows/artifact.py
  src/hera/workflows/runner.py
  src/hera/workflows/script.py
  tests/test_script_annotations.py
Labels: semver:patch, type:bug

#860 Use http link for authentication walkthrough in README
  README.md
Labels: semver:patch, type:documentation

#868 Add labels to dependanbot
  .github/dependabot.yml
Labels: semver:patch, type:enhancement

#870 Add another talk to the README
  README.md
Labels: semver:patch, type:documentation

#873 Use diff join for workflow links
  scripts/service.py
  src/hera/workflows/service.py
  tests/test_unit/test_cron_workflow.py
  tests/test_unit/test_workflow.py
Labels: semver:patch, type:bug

#859 Fix _is_str_kwarg_of for annotated parameters
  src/hera/workflows/runner.py
  tests/script_runner/parameter_inputs.py
  tests/test_runner.py
Labels: semver:patch, type:bug

#874 Add support for modifying field properties prior to model generation
  docs/examples/workflows/upstream/daemon_nginx.md
  examples/workflows/upstream/daemon-nginx.yaml
  scripts/spec.py
  src/hera/events/models/io/k8s/api/core/v1.py
  src/hera/events/models/io/k8s/api/core/v1.pyi
  src/hera/workflows/models/io/k8s/api/core/v1.py
  src/hera/workflows/models/io/k8s/api/core/v1.pyi
Labels: semver:patch, type:bug

#850 Graduate script runner
  docs/examples/workflows/callable_coinflip.md
  docs/examples/workflows/callable_script.md
  docs/examples/workflows/script_annotations_artifact_custom_volume.md
  docs/examples/workflows/script_annotations_artifact_loaders.md
  docs/examples/workflows/script_annotations_artifact_outputs_defaults.md
  docs/examples/workflows/script_annotations_artifact_passing.md
  docs/examples/workflows/script_annotations_inputs.md
  docs/examples/workflows/script_annotations_outputs.md
  docs/user-guides/scripts.md
  docs/walk-through/advanced-hera-features.md
  examples/workflows/callable_coinflip.py
  examples/workflows/callable_script.py
  examples/workflows/script_annotations_artifact_custom_volume.py
  examples/workflows/script_annotations_artifact_loaders.py
  examples/workflows/script_annotations_artifact_outputs_defaults.py
  examples/workflows/script_annotations_artifact_passing.py
  examples/workflows/script_annotations_inputs.py
  examples/workflows/script_annotations_outputs.py
  src/hera/workflows/script.py
  tests/script_annotations/outputs.py
  tests/script_runner/annotated_outputs.py
  tests/script_runner/artifact_loaders.py
  tests/script_runner/artifact_with_invalid_loader.py
  tests/script_runner/parameter_inputs.py
  tests/script_runner/unknown_annotation_types.py
  tests/test_runner.py
Labels: type:enhancement, semver:minor

#875 Fix incorrect aggregation of volume mount and dynamic volumes created via Hera
  docs/examples/workflows/volume_mount.md
  examples/workflows/volume-mount.yaml
  examples/workflows/volume_mount.py
  src/hera/workflows/_mixins.py
Labels: semver:patch, type:bug

#877 Remap `image_pull_policy` field on `Container` from `ImagePullPolicy` enum to `str`
  scripts/spec.py
  src/hera/events/models/io/k8s/api/core/v1.py
  src/hera/events/models/io/k8s/api/core/v1.pyi
  src/hera/workflows/models/io/k8s/api/core/v1.py
  src/hera/workflows/models/io/k8s/api/core/v1.pyi
Labels: semver:patch, type:bug

#876 Implement get_parameter API on IO mixin and add tests
  docs/examples/workflows/callable_dag_with_param_get.md
  docs/examples/workflows/upstream/loops_arbitrary_sequential_steps.md
  docs/examples/workflows/upstream/parallelism_nested.md
  examples/workflows/callable-dag-with-param-get.yaml
  examples/workflows/callable_dag_with_param_get.py
  examples/workflows/upstream/loops_arbitrary_sequential_steps.py
  examples/workflows/upstream/parallelism_nested.py
  src/hera/workflows/_mixins.py
  src/hera/workflows/dag.py
  src/hera/workflows/parameter.py
  tests/test_unit/test_mixins.py
Labels: type:enhancement, semver:minor

#878 Update "bug occurs when" section
  .github/ISSUE_TEMPLATE/🐛-bug-report.md
Labels: type:skip-changelog

#880 Revert "Add Pydantic `Extra.forbid` to shared base model config "
  docs/examples/workflows-examples.md
  docs/examples/workflows/upstream/webhdfs_input_output_artifacts.md
  docs/examples/workflows/volume_mounts_nfs.md
  examples/workflows/upstream/webhdfs-input-output-artifacts.yaml
  examples/workflows/upstream/webhdfs_input_output_artifacts.py
  examples/workflows/volume_mounts_nfs.py
  src/hera/shared/_base_model.py
  src/hera/workflows/_mixins.py
  src/hera/workflows/artifact.py
  src/hera/workflows/user_container.py
  tests/script_annotations_inputs_regression/script_annotations_artifacts_mode_recurse_new.py
  tests/script_annotations_inputs_regression/script_annotations_artifacts_mode_recurse_old.py
  tests/script_annotations_inputs_regression/script_annotations_artifacts_oss_new.py
  tests/script_annotations_inputs_regression/script_annotations_artifacts_oss_old.py
  tests/script_annotations_inputs_regression/script_annotations_artifacts_s3_new.py
  tests/script_annotations_inputs_regression/script_annotations_artifacts_s3_old.py
  tests/script_annotations_inputs_regression/script_annotations_artifacts_subpath_new.py
  tests/script_annotations_inputs_regression/script_annotations_artifacts_subpath_old.py
  tests/script_annotations_inputs_regression/script_annotations_configmap_new.py
  tests/script_annotations_inputs_regression/script_annotations_configmap_old.py
  tests/test_script_annotations.py
  tests/test_unit/test_user_container.py
Labels: semver:patch, type:bug
