Repository argoproj-labs/hera, pull requests merged in 2023-08, with the labels that each got.

#731 Add missing `ImagePullPolicy.value` for container sets that use `str` vs `ImagePullPolicy`
  src/hera/workflows/container_set.py
Labels: semver:patch, type:bug

#734 Move extensive task docstring to getting-started.md
  docs/getting-started/walk-through/dag.md
  src/hera/workflows/container_set.py
  src/hera/workflows/cron_workflow.py
  src/hera/workflows/dag.py
  src/hera/workflows/task.py
  src/hera/workflows/workflow.py
  src/hera/workflows/workflow_template.py
Labels: semver:patch, type:documentation

#737 Fix links and doc style headings
  src/hera/workflows/container_set.py
  src/hera/workflows/cron_workflow.py
  src/hera/workflows/metrics.py
  src/hera/workflows/resources.py
  src/hera/workflows/task.py
  src/hera/workflows/volume.py
  src/hera/workflows/workflow.py
  src/hera/workflows/workflow_template.py
Labels: semver:patch, type:documentation

#739 Use the runner constructor in Parameter/Artifact annotation examples
  docs/examples/workflows/script_annotations.md
  examples/workflows/script-annotations.yaml
  examples/workflows/script_annotations.py
  tests/annotation_regression_examples/script_annotations_artifacts_artifactory_new.py
  tests/annotation_regression_examples/script_annotations_artifacts_artifactory_old.py
  tests/annotation_regression_examples/script_annotations_artifacts_azure_new.py
  tests/annotation_regression_examples/script_annotations_artifacts_azure_old.py
  tests/annotation_regression_examples/script_annotations_artifacts_gcs_new.py
  tests/annotation_regression_examples/script_annotations_artifacts_gcs_old.py
  tests/annotation_regression_examples/script_annotations_artifacts_git_new.py
  tests/annotation_regression_examples/script_annotations_artifacts_git_old.py
  tests/annotation_regression_examples/script_annotations_artifacts_hdfs_new.py
  tests/annotation_regression_examples/script_annotations_artifacts_hdfs_old.py
  tests/annotation_regression_examples/script_annotations_artifacts_http_new.py
  tests/annotation_regression_examples/script_annotations_artifacts_http_old.py
  tests/annotation_regression_examples/script_annotations_artifacts_mode_new.py
  tests/annotation_regression_examples/script_annotations_artifacts_mode_old.py
  tests/annotation_regression_examples/script_annotations_artifacts_mode_recurse_new.py
  tests/annotation_regression_examples/script_annotations_artifacts_mode_recurse_old.py
  tests/annotation_regression_examples/script_annotations_artifacts_optional_new.py
  tests/annotation_regression_examples/script_annotations_artifacts_optional_old.py
  tests/annotation_regression_examples/script_annotations_artifacts_oss_new.py
  tests/annotation_regression_examples/script_annotations_artifacts_oss_old.py
  tests/annotation_regression_examples/script_annotations_artifacts_raw_new.py
  tests/annotation_regression_examples/script_annotations_artifacts_raw_old.py
  tests/annotation_regression_examples/script_annotations_artifacts_s3_new.py
  tests/annotation_regression_examples/script_annotations_artifacts_s3_old.py
  tests/annotation_regression_examples/script_annotations_artifacts_subpath_new.py
  tests/annotation_regression_examples/script_annotations_artifacts_subpath_old.py
  tests/artifact_annotations/script_annotations_artifact_file.py
  tests/artifact_annotations/script_annotations_artifact_file_with_path.py
  tests/artifact_annotations/script_annotations_artifact_object.py
  tests/artifact_annotations/script_annotations_artifact_path.py
  tests/artifact_annotations/script_annotations_artifact_wrong_loader.py
Labels: type:skip-changelog

#735 Add testable support for configmaps
  docs/examples/workflows-examples.md
  docs/examples/workflows/script_auto_infer.md
  examples/workflows/script-auto-infer.yaml
  src/hera/workflows/script.py
  tests/configmap_tests/configmap_new.py
  tests/configmap_tests/configmap_old.py
  tests/test_script_annotations_configmap.py
Labels: type:enhancement, semver:minor

#747 Add missing `__all__` to cluster workflow template
  src/hera/workflows/__init__.py
  src/hera/workflows/cluster_workflow_template.py
Labels: semver:patch, type:bug

#751 Adjust container fanout example
  docs/examples/workflows/dynamic_fanout_container.md
  examples/workflows/dynamic-fanout-container.yaml
  examples/workflows/dynamic_fanout_container.py
  examples/workflows/upstream/suspend-template.upstream.yaml
Labels: semver:patch, type:documentation

#750 Adjust dynamic fanout/fanin example
  docs/examples/workflows/dynamic_fanout_fanin.md
  examples/workflows/dynamic-fanout-fanin.yaml
  examples/workflows/dynamic_fanout_fanin.py
Labels: semver:patch, type:documentation
