Repository argoproj-labs/hera, pull requests merged in 2023-04, with the labels that each got.

#542 Fix global config issue with script command
  Makefile
  docs/examples/workflows/global_config.md
  examples/workflows/global-config.yaml
  examples/workflows/global_config.py
  poetry.lock
  pyproject.toml
  src/hera/shared/_global_config.py
  src/hera/workflows/script.py
Labels: semver:patch, type:bug

#544 Add check that auto-genned params do not have already set artifact names
  docs/examples/workflows/script_auto_infer.md
  examples/workflows/script-auto-infer.yaml
  examples/workflows/script_auto_infer.py
  src/hera/workflows/_mixins.py
  src/hera/workflows/script.py
Labels: semver:patch, type:bug

#549 Add note on <5.0.0 Hera installs
  README.md
Labels: semver:patch, type:documentation

#543 Add a script constructor that allows for flexible script construction and add a robust runner mode
  docs/examples/workflows/callable_coinflip.md
  docs/examples/workflows/callable_script.md
  docs/examples/workflows/coinflip.md
  docs/examples/workflows/complex_deps.md
  docs/examples/workflows/dag_with_script_param_passing.md
  docs/examples/workflows/dynamic_volumes.md
  docs/examples/workflows/global_config.md
  docs/examples/workflows/multi_env.md
  docs/examples/workflows/script_auto_infer.md
  docs/examples/workflows/script_with_default_params.md
  docs/examples/workflows/volume_mounts.md
  examples/workflows/callable-coinflip.yaml
  examples/workflows/callable-script.yaml
  examples/workflows/callable_coinflip.py
  examples/workflows/callable_script.py
  examples/workflows/coinflip.yaml
  examples/workflows/complex-deps.yaml
  examples/workflows/dag-with-script-param-passing.yaml
  examples/workflows/dynamic-volumes.yaml
  examples/workflows/global-config.yaml
  examples/workflows/global_config.py
  examples/workflows/multi-env.yaml
  examples/workflows/script-auto-infer.yaml
  examples/workflows/script-with-default-params.yaml
  examples/workflows/volume-mounts.yaml
  src/hera/shared/__init__.py
  src/hera/shared/_base_model.py
  src/hera/shared/_global_config.py
  src/hera/shared/serialization.py
  src/hera/workflows/__init__.py
  src/hera/workflows/_context.py
  src/hera/workflows/_mixins.py
  src/hera/workflows/runner.py
  src/hera/workflows/script.py
  tests/test_hooks.py
  tests/test_runner.py
Labels: type:enhancement, semver:minor

#551 WorkflowsService doesn't respect verify_ssl=False
  scripts/service.py
  src/hera/events/service.py
  src/hera/workflows/service.py
Labels: semver:patch, type:bug

#553 Fix: Use correct parameter names for Create and Lint requests
  src/hera/workflows/cron_workflow.py
  src/hera/workflows/workflow_template.py
Labels: semver:patch, type:bug

#555 Add missing typing extensions to docs
  docs/requirements.txt
Labels: semver:patch, type:bug

#554 Script.resources is not the same as ModelTemplate.resource
  docs/examples/workflows/script_with_resources.md
  examples/workflows/script-with-resources.yaml
  examples/workflows/script_with_resources.py
  src/hera/workflows/script.py
Labels: semver:patch, type:bug

#557 Fix service generator, regen services
  scripts/service.py
  src/hera/events/service.py
  src/hera/workflows/cron_workflow.py
  src/hera/workflows/service.py
  src/hera/workflows/workflow.py
  src/hera/workflows/workflow_template.py
Labels: semver:patch, type:enhancement

#558 Fix validation error for retry strategy
  docs/examples/workflows/upstream/retry_script.md
  examples/workflows/upstream/retry-script.upstream.yaml
  examples/workflows/upstream/retry-script.yaml
  examples/workflows/upstream/retry_script.py
  src/hera/workflows/retry_strategy.py
Labels: semver:patch, type:bug

#565 Fix output param getter
  docs/examples/workflows/dag-with-script-output-param-passing.md
  docs/examples/workflows/upstream/retry_script.md
  examples/workflows/dag-with-script-output-param-passing.py
  examples/workflows/dag-with-script-output-param-passing.yaml
  examples/workflows/upstream/retry-script.upstream.yaml
  examples/workflows/upstream/retry-script.yaml
  examples/workflows/upstream/retry_script.py
  src/hera/workflows/retry_strategy.py
  src/hera/workflows/task.py
Labels: semver:patch, type:bug

#566 Add more examples
  docs/examples/workflows/upstream/archive_location.md
  docs/examples/workflows/upstream/arguments_parameters.md
  docs/examples/workflows/upstream/arguments_parameters_from_configmap.md
  docs/examples/workflows/upstream/cluster_workflow_template__cluster_wftmpl_dag.md
  docs/examples/workflows/upstream/cluster_workflow_template__mixed_cluster_namespaced_wftmpl_steps.md
  docs/examples/workflows/upstream/cluster_workflow_template__workflow_template_ref_with_entrypoint_arg_passing.md
  docs/examples/workflows/upstream/workflow_event_binding__event_consumer_workflowtemplate.md
  docs/examples/workflows/upstream/workflow_template__retry_with_steps.md
  docs/examples/workflows/upstream/workflow_template__steps.md
  docs/examples/workflows/upstream/workflow_template__workflow_archive_logs.md
  docs/examples/workflows/upstream/workflow_template__workflow_template_ref_with_entrypoint_arg_passing.md
  examples/workflows/upstream/archive-location.upstream.yaml
  examples/workflows/upstream/archive-location.yaml
  examples/workflows/upstream/archive_location.py
  examples/workflows/upstream/arguments-parameters-from-configmap.upstream.yaml
  examples/workflows/upstream/arguments-parameters-from-configmap.yaml
  examples/workflows/upstream/arguments-parameters.upstream.yaml
  examples/workflows/upstream/arguments-parameters.yaml
  examples/workflows/upstream/arguments_parameters.py
  examples/workflows/upstream/arguments_parameters_from_configmap.py
  examples/workflows/upstream/cluster-workflow-template--cluster-wftmpl-dag.upstream.yaml
  examples/workflows/upstream/cluster-workflow-template--cluster-wftmpl-dag.yaml
  examples/workflows/upstream/cluster-workflow-template--mixed-cluster-namespaced-wftmpl-steps.upstream.yaml
  examples/workflows/upstream/cluster-workflow-template--mixed-cluster-namespaced-wftmpl-steps.yaml
  examples/workflows/upstream/cluster-workflow-template--workflow-template-ref-with-entrypoint-arg-passing.upstream.yaml
  examples/workflows/upstream/cluster-workflow-template--workflow-template-ref-with-entrypoint-arg-passing.yaml
  examples/workflows/upstream/cluster_workflow_template__cluster_wftmpl_dag.py
  examples/workflows/upstream/cluster_workflow_template__mixed_cluster_namespaced_wftmpl_steps.py
  examples/workflows/upstream/cluster_workflow_template__workflow_template_ref_with_entrypoint_arg_passing.py
  examples/workflows/upstream/workflow-event-binding--event-consumer-workflowtemplate.upstream.yaml
  examples/workflows/upstream/workflow-event-binding--event-consumer-workflowtemplate.yaml
  examples/workflows/upstream/workflow-template--retry-with-steps.upstream.yaml
  examples/workflows/upstream/workflow-template--retry-with-steps.yaml
  examples/workflows/upstream/workflow-template--steps.upstream.yaml
  examples/workflows/upstream/workflow-template--steps.yaml
  examples/workflows/upstream/workflow-template--workflow-archive-logs.upstream.yaml
  examples/workflows/upstream/workflow-template--workflow-archive-logs.yaml
  examples/workflows/upstream/workflow-template--workflow-template-ref-with-entrypoint-arg-passing.upstream.yaml
  examples/workflows/upstream/workflow-template--workflow-template-ref-with-entrypoint-arg-passing.yaml
  examples/workflows/upstream/workflow_event_binding__event_consumer_workflowtemplate.py
  examples/workflows/upstream/workflow_template__retry_with_steps.py
  examples/workflows/upstream/workflow_template__steps.py
  examples/workflows/upstream/workflow_template__workflow_archive_logs.py
  examples/workflows/upstream/workflow_template__workflow_template_ref_with_entrypoint_arg_passing.py
Labels: semver:patch, type:documentation

#569 Add before/after rename stats to README
  README.md
Labels: semver:patch, type:documentation

#570 Fix hera workflows stats
  README.md
Labels: semver:patch, type:bug

#574 Fix inline script parsing issues
  docs/examples/workflows/coinflip.md
  docs/examples/workflows/complex_deps.md
  docs/examples/workflows/dag-with-script-output-param-passing.md
  docs/examples/workflows/dag_conditional_parameters.md
  docs/examples/workflows/dag_diamond_with_callable_decorators.md
  docs/examples/workflows/dag_diamond_with_callable_script.md
  docs/examples/workflows/dag_with_script_param_passing.md
  docs/examples/workflows/dynamic_volumes.md
  docs/examples/workflows/global_config.md
  docs/examples/workflows/multi_env.md
  docs/examples/workflows/script_auto_infer.md
  docs/examples/workflows/script_variations.md
  docs/examples/workflows/script_with_default_params.md
  docs/examples/workflows/script_with_resources.md
  docs/examples/workflows/upstream/coinflip.md
  docs/examples/workflows/upstream/colored_logs.md
  docs/examples/workflows/upstream/conditional_artifacts.md
  docs/examples/workflows/upstream/container_set_template__outputs_result_workflow.md
  docs/examples/workflows/upstream/dag_conditional_parameters.md
  docs/examples/workflows/upstream/exit_handler_with_artifacts.md
  docs/examples/workflows/upstream/loops_param_result.md
  docs/examples/workflows/upstream/retry_script.md
  docs/examples/workflows/volume_mounts.md
  examples/workflows/coinflip.yaml
  examples/workflows/complex-deps.yaml
  examples/workflows/dag-conditional-parameters.yaml
  examples/workflows/dag-diamond-with-callable-decorators.yaml
  examples/workflows/dag-diamond-with-callable-script.yaml
  examples/workflows/dag-with-script-output-param-passing.yaml
  examples/workflows/dag-with-script-param-passing.yaml
  examples/workflows/dynamic-volumes.yaml
  examples/workflows/global-config.yaml
  examples/workflows/multi-env.yaml
  examples/workflows/script-auto-infer.yaml
  examples/workflows/script-variations.yaml
  examples/workflows/script-with-default-params.yaml
  examples/workflows/script-with-resources.yaml
  examples/workflows/script_variations.py
  examples/workflows/upstream/coinflip.yaml
  examples/workflows/upstream/colored-logs.yaml
  examples/workflows/upstream/conditional-artifacts.yaml
  examples/workflows/upstream/container-set-template--outputs-result-workflow.yaml
  examples/workflows/upstream/dag-conditional-parameters.yaml
  examples/workflows/upstream/exit-handler-with-artifacts.yaml
  examples/workflows/upstream/loops-param-result.yaml
  examples/workflows/upstream/retry-script.yaml
  examples/workflows/volume-mounts.yaml
  src/hera/workflows/_unparse.py
  src/hera/workflows/script.py
Labels: semver:patch, type:bug

#578 Fix conditional on task status to string conversion
  docs/examples/workflows/dag_conditional_on_task_status.md
  examples/workflows/dag-conditional-on-task-status.yaml
  examples/workflows/dag_conditional_on_task_status.py
  src/hera/workflows/task.py
Labels: semver:patch, type:bug

#586 fix image pull policy validation error
  docs/examples/workflows/script_with_image_pull_policy.md
  examples/workflows/script-with-image-pull-policy.yaml
  examples/workflows/script_with_image_pull_policy.py
  src/hera/workflows/_mixins.py
Labels: semver:patch, type:bug

#587 fix: broken URLs on Windows due to os.path.join()
  scripts/service.py
  src/hera/events/service.py
  src/hera/workflows/service.py
Labels: semver:patch, type:bug

#590 Make context async-friendly
  src/hera/workflows/_context.py
  tests/test_context.py
Labels: semver:patch, type:bug

#592 Fix script decorator to properly wrap the underlying function
  src/hera/workflows/script.py
Labels: semver:patch, type:bug

#593 Add workflow of workflows example
  docs/examples/workflows/upstream/workflow_of_workflows.md
  examples/workflows/upstream/workflow-of-workflows.upstream.yaml
  examples/workflows/upstream/workflow-of-workflows.yaml
  examples/workflows/upstream/workflow_of_workflows.py
Labels: semver:patch, type:documentation

#596 Add global_parameters upstream example
  docs/examples/workflows/upstream/global_parameters.md
  examples/workflows/upstream/global-parameters.upstream.yaml
  examples/workflows/upstream/global-parameters.yaml
  examples/workflows/upstream/global_parameters.py
Labels: semver:patch, type:documentation

#597 Add missing examples test
  Makefile
  tests/test_remaining_examples.py
Labels: semver:patch, type:documentation

#598 Add script_artifact_passing example
  docs/examples/workflows/script_artifact_passing.md
  examples/workflows/script-artifact-passing.yaml
  examples/workflows/script_artifact_passing.py
Labels: semver:patch, type:documentation

#601 Make suspend template callable, add suspend examples
  docs/examples/workflows/upstream/suspend-template-outputs.md
  docs/examples/workflows/upstream/suspend-template.md
  examples/workflows/upstream/suspend-template-outputs.py
  examples/workflows/upstream/suspend-template-outputs.upstream.yaml
  examples/workflows/upstream/suspend-template-outputs.yaml
  examples/workflows/upstream/suspend-template.py
  examples/workflows/upstream/suspend-template.upstream.yaml
  examples/workflows/upstream/suspend-template.yaml
  src/hera/workflows/suspend.py
  src/hera/workflows/workflow.py
Labels: semver:patch, type:enhancement

#602 Add github templates
  .github/ISSUE_TEMPLATE/❓-i-have-a-question.md
  .github/ISSUE_TEMPLATE/🐛-bug-report.md
  .github/ISSUE_TEMPLATE/🚀-feature-request.md
  .github/pull_request_template.md
Labels: semver:patch, type:documentation

#604 Fix `script_variations.py` example workflow
  docs/examples/workflows/script_variations.md
  examples/workflows/script-variations.yaml
  examples/workflows/script_variations.py
Labels: semver:patch, type:documentation
