Repository argoproj-labs/hera, pull requests merged in 2023-12, with the labels that each got.

#889 fix image pull policy prediction
  src/hera/workflows/_mixins.py
  src/hera/workflows/container_set.py
  src/hera/workflows/script.py
  tests/test_unit/test_container.py
  tests/test_unit/test_mixins.py
  tests/test_unit/test_workflow.py
Labels: semver:patch, type:bug

#887 Add on-cluster workflow test to CI
  .github/workflows/cicd.yaml
  Makefile
  examples/workflows-examples.md
  pyproject.toml
  tests/test_submission.py
Labels: semver:patch, type:task, github_actions

#897 Add optional support for pydantic v1 models when v2 is installed
  examples/workflows/scripts/callable-script-v1.yaml
  examples/workflows/scripts/callable_script_v1.py
  src/hera/shared/_pydantic.py
  src/hera/workflows/runner.py
  src/hera/workflows/script.py
  tests/script_runner/parameter_inputs.py
  tests/test_runner.py
Labels: type:enhancement, semver:minor

#899 Add another Hera blog
  README.md
Labels: semver:patch, type:documentation

#886 Add hera CLI and implement `generate yaml`.
  .github/workflows/cicd.yaml
  poetry.lock
  pyproject.toml
  src/hera/__main__.py
  src/hera/_cli/__init__.py
  src/hera/_cli/base.py
  src/hera/_cli/generate/__init__.py
  src/hera/_cli/generate/yaml.py
  tests/cli/__init__.py
  tests/cli/examples/cluster_workflow_template.py
  tests/cli/examples/multiple_workflow.py
  tests/cli/examples/single_workflow.py
  tests/cli/examples/skipped
  tests/cli/examples/workflow_template.py
  tests/cli/test_generate_yaml.py
  tests/cli/test_main.py
  tests/test_unit/__init__.py
Labels: type:enhancement, semver:minor

#905 Refactor "one or many" typed Hera values
  Makefile
  src/hera/workflows/_mixins.py
  tests/test_unit/test_mixins.py
Labels: semver:patch, type:task
