Repository argoproj-labs/hera, pull requests merged in 2023-02, with the labels that each got.

#415 Remove subset type within Union
  src/hera/io.py
  src/hera/task.py
  tests/test_version.py
Labels: semver:patch, type:enhancement

#413 Simplify Task and Workflow script comparisons
  tests/test_task.py
  tests/test_workflow.py
Labels: semver:patch, type:skip-changelog

#410 Ephemeral storage
  src/hera/resources.py
  tests/test_resources.py
Labels: type:enhancement, semver:minor

#421 Remove docs version because auto-publishing is not in sync with docs
  docs/conf.py
Labels: semver:patch, type:documentation

#428 Parameter bug fixes
  src/hera/parameter.py
  src/hera/task.py
  src/hera/value_from.py
  tests/test_parameter.py
  tests/test_task.py
  tests/test_value_from.py
Labels: semver:patch, type:bug

#431 Fix value-from for config map references
  src/hera/value_from.py
  tests/test_value_from.py
Labels: semver:patch, type:bug

#432 Remove restrictions from enums/defaults
  src/hera/parameter.py
  tests/test_parameter.py
Labels: semver:patch, type:bug

#420 [2/N] Generate all `workflows` and `events` models
  Makefile
  docs/generate.py
  poetry.lock
  pyproject.toml
  scripts/models.py
  src/hera/events/__init__.py
  src/hera/events/_base_model.py
  src/hera/events/models/__init__.py
  src/hera/events/models/eventsource.py
  src/hera/events/models/google/__init__.py
  src/hera/events/models/google/protobuf.py
  src/hera/events/models/grpc/gateway/__init__.py
  src/hera/events/models/grpc/gateway/runtime.py
  src/hera/events/models/io/argoproj/events/__init__.py
  src/hera/events/models/io/argoproj/events/v1alpha1.py
  src/hera/events/models/io/argoproj/workflow/__init__.py
  src/hera/events/models/io/argoproj/workflow/v1alpha1.py
  src/hera/events/models/io/k8s/api/core/__init__.py
  src/hera/events/models/io/k8s/api/core/v1.py
  src/hera/events/models/io/k8s/api/policy/__init__.py
  src/hera/events/models/io/k8s/api/policy/v1beta1.py
  src/hera/events/models/io/k8s/apimachinery/pkg/api/__init__.py
  src/hera/events/models/io/k8s/apimachinery/pkg/api/resource.py
  src/hera/events/models/io/k8s/apimachinery/pkg/apis/meta/__init__.py
  src/hera/events/models/io/k8s/apimachinery/pkg/apis/meta/v1.py
  src/hera/events/models/io/k8s/apimachinery/pkg/util/__init__.py
  src/hera/events/models/io/k8s/apimachinery/pkg/util/intstr.py
  src/hera/events/models/sensor.py
  src/hera/expr/_node.py
  src/hera/workflows/__init__.py
  src/hera/workflows/_base_model.py
  src/hera/workflows/models/__init__.py
  src/hera/workflows/models/eventsource.py
  src/hera/workflows/models/google/__init__.py
  src/hera/workflows/models/google/protobuf.py
  src/hera/workflows/models/grpc/gateway/__init__.py
  src/hera/workflows/models/grpc/gateway/runtime.py
  src/hera/workflows/models/io/argoproj/events/__init__.py
  src/hera/workflows/models/io/argoproj/events/v1alpha1.py
  src/hera/workflows/models/io/argoproj/workflow/__init__.py
  src/hera/workflows/models/io/argoproj/workflow/v1alpha1.py
  src/hera/workflows/models/io/k8s/api/core/__init__.py
  src/hera/workflows/models/io/k8s/api/core/v1.py
  src/hera/workflows/models/io/k8s/api/policy/__init__.py
  src/hera/workflows/models/io/k8s/api/policy/v1beta1.py
  src/hera/workflows/models/io/k8s/apimachinery/pkg/api/__init__.py
  src/hera/workflows/models/io/k8s/apimachinery/pkg/api/resource.py
  src/hera/workflows/models/io/k8s/apimachinery/pkg/apis/meta/__init__.py
  src/hera/workflows/models/io/k8s/apimachinery/pkg/apis/meta/v1.py
  src/hera/workflows/models/io/k8s/apimachinery/pkg/util/__init__.py
  src/hera/workflows/models/io/k8s/apimachinery/pkg/util/intstr.py
  src/hera/workflows/models/sensor.py
Labels: type:enhancement, semver:major

#439 Enable CI/CD on hera/v5 branch
  .github/workflows/cicd.yaml
Labels: semver:patch, type:enhancement
