Repository argoproj-labs/hera, pull requests merged in 2024-09, with the labels that each got.

#1168 Allow Artifact/Parameter in any position in `Annotated` metadata
  src/hera/shared/_type_util.py
  src/hera/workflows/_meta_mixins.py
  src/hera/workflows/_mixins.py
  src/hera/workflows/_runner/script_annotations_util.py
  src/hera/workflows/_runner/util.py
  src/hera/workflows/cron_workflow.py
  src/hera/workflows/io/_io_mixins.py
  src/hera/workflows/script.py
  tests/script_runner/parameter_inputs.py
  tests/script_runner/parameter_with_complex_types.py
  tests/script_runner/pydantic_io_v2_invalid.py
  tests/test_runner.py
  tests/test_unit/test_script.py
  tests/test_unit/test_shared_type_utils.py
Labels: type:enhancement, semver:minor

#1186 Support various output tuple annotation
  src/hera/workflows/script.py
  tests/script_runner/parameter_with_complex_types.py
  tests/test_runner.py
Labels: semver:patch, type:bug

#1183 Add optional Session to Service to be able to reuse connections
  scripts/service.py
  src/hera/events/service.py
  src/hera/workflows/service.py
  tests/test_workflows_service.py
Labels: type:enhancement, semver:minor

#1199 Docs fixes/improvements
  README.md
  docs/README.md
  docs/contributing/history.md
  docs/user-guides/expr.md
  docs/user-guides/script-annotations.md
  docs/user-guides/script-basics.md
  docs/user-guides/script-runner-io.md
  docs/walk-through/pydantic-support.md
  pyproject.toml
  src/hera/__init__.py
Labels: semver:patch, type:documentation

#1201 Remove references to needing to enable second flag
  docs/user-guides/script-runner-io.md
  docs/walk-through/advanced-hera-features.md
Labels: semver:patch, type:documentation

#1203 Remove 3.8 from status checks so #1202 can pass
  .github/workflows/cicd.yaml
Labels: type:skip-changelog

#1197 Error on Parameter default kwarg usage for inputs
  docs/examples/workflows/experimental/new_dag_decorator_params.md
  docs/examples/workflows/experimental/new_steps_decorator_with_parallel_steps.md
  docs/user-guides/script-annotations.md
  examples/workflows/experimental/new_dag_decorator_params.py
  examples/workflows/experimental/new_steps_decorator_with_parallel_steps.py
  src/hera/shared/_global_config.py
  src/hera/workflows/io/_io_mixins.py
  src/hera/workflows/script.py
  tests/test_decorators.py
  tests/test_script_annotations.py
Labels: semver:minor, type:informational

#1211 Fix type annotations on template decorators
  src/hera/workflows/_meta_mixins.py
  tests/typehints/test_template_decorator.py
Labels: semver:patch, type:bug, python

#1212 fix: update dask use case example
  docs/examples/workflows/use-cases/dask.md
  examples/workflows/use_cases/dask.py
  examples/workflows/use_cases/dask.yaml
Labels: semver:patch, type:documentation

#1213 Remove use of skip_defaults
  scripts/service.py
  src/hera/events/service.py
  src/hera/workflows/service.py
Labels: semver:patch, type:task

#1214 Disable warnings from model_dump
  src/hera/workflows/io/_io_mixins.py
Labels: semver:patch, type:bug

#1217 Fix unclosed file warning
  src/hera/workflows/_runner/script_annotations_util.py
Labels: semver:patch, type:bug
