Repository argoproj-labs/hera, pull requests merged in 2024-11, with the labels that each got.

#1258 Update cicd.yaml
  .github/workflows/cicd.yaml
Labels: type:skip-changelog

#1259 Combine all code coverages in CI
  Makefile
Labels: type:skip-changelog

#1249 Support Literal types in script runner
  src/hera/shared/_type_util.py
  src/hera/workflows/script.py
  tests/script_annotations/annotated_literals.py
  tests/script_annotations/literals.py
  tests/script_annotations/pydantic_io_literals.py
  tests/script_runner/parameter_inputs.py
  tests/test_runner.py
  tests/test_script_annotations.py
  tests/test_unit/test_script.py
  tests/test_unit/test_shared_type_utils.py
Labels: semver:patch, type:enhancement

#1265 Add ArgoCon NA24 talk
  README.md
Labels: semver:patch, type:documentation

#1267 Remove myself from maintainers as per Slack post in CNCF :)
  .github/CODEOWNERS
  CODE_OF_CONDUCT.md
  MEMBERS.md
  pyproject.toml
Labels: type:skip-changelog

#1264 Add a local build-docs make target
  Makefile
  mkdocs.yml
Labels: type:skip-changelog

#1278 Remove override for `default` usage in `Parameter` annotations
  src/hera/shared/_global_config.py
  src/hera/workflows/io/_io_mixins.py
  src/hera/workflows/script.py
  tests/test_script_annotations.py
  tests/workflow_decorators/steps.py
Labels: type:task, semver:minor

#1279 Add emeritus + license block to README.md
  README.md
Labels: type:skip-changelog

#1280 Add @alicederyn as an approver
  .github/CODEOWNERS
  MEMBERS.md
Labels: type:skip-changelog
