Repository argoproj-labs/hera, pull requests merged in 2024-03, with the labels that each got.

#974 Fix RunnerInput defaults
  docs/examples/workflows-examples.md
  docs/examples/workflows/experimental/script_runner_io.md
  docs/examples/workflows/template_level_volume.md
  docs/user-guides/script-annotations.md
  docs/user-guides/script-basics.md
  docs/user-guides/script-runner-io.md
  docs/user-guides/scripts.md
  docs/walk-through/advanced-hera-features.md
  docs/walk-through/hello-world.md
  docs/walk-through/pydantic-support.md
  examples/workflows/experimental/script-pydantic-io.yaml
  examples/workflows/experimental/script-runner-io.yaml
  examples/workflows/experimental/script_runner_io.py
  examples/workflows/template-level-volume.yaml
  examples/workflows/upstream/title-and-description-with-markdown.upstream.yaml
  examples/workflows/upstream/withsequence-nested-result.upstream.yaml
  mkdocs.yml
  src/hera/workflows/_runner/__init__.py
  src/hera/workflows/_runner/script_annotations_util.py
  src/hera/workflows/_runner/util.py
  src/hera/workflows/io/v1.py
  src/hera/workflows/io/v2.py
  src/hera/workflows/runner.py
  tests/script_annotations/pydantic_io_v1.py
  tests/script_annotations/pydantic_io_v1_strs.py
  tests/script_annotations/pydantic_io_v2.py
  tests/script_annotations/pydantic_io_v2_strs.py
  tests/test_runner.py
  tests/test_script_annotations.py
  tests/test_unit/test_script_annotations_util.py
Labels: semver:patch, type:bug

#989 Fix `to` generating to folder and refactor tests
  src/hera/_cli/generate/yaml.py
  tests/cli/test_generate_yaml.py
Labels: semver:patch, type:bug

#996 Tidy up runner tests
  tests/conftest.py
  tests/script_runner/annotated_outputs.py
  tests/test_runner.py
Labels: type:skip-changelog

#1002 Add hera tour to walkthrough
  CONTRIBUTING.md
  Makefile
  docs/examples/workflows/dags/dag_diamond_with_callable_decorators.md
  docs/examples/workflows/upstream/dag_diamond.md
  docs/examples/workflows/use-cases/testing_templates_and_workflows.md
  docs/walk-through/about-hera.md
  docs/walk-through/hera-tour.md
  examples/workflows/dags/dag-diamond-with-callable-decorators.yaml
  examples/workflows/dags/dag_diamond_with_callable_decorators.py
  examples/workflows/upstream/dag_diamond.py
  examples/workflows/use_cases/testing-templates-and-workflows.yaml
  examples/workflows/use_cases/testing_templates_and_workflows.py
  mkdocs.yml
  tests/test_submission.py
Labels: semver:patch, type:documentation

#1007 Add Elliot's talk to the README
  README.md
Labels: semver:patch, type:task
