Repository argoproj-labs/hera, pull requests merged in 2024-02, with the labels that each got.

#950 fix: Improve linting/editor experience for hera models.
  src/hera/shared/_global_config.py
  src/hera/shared/_pydantic.py
  src/hera/workflows/_mixins.py
  src/hera/workflows/io.py
Labels: semver:patch, type:bug

#937 Support passing Hera Parameter/ModelParameter as dictionary input to tasks
  src/hera/workflows/_mixins.py
  tests/test_unit/test_arguments.py
Labels: semver:patch, type:bug

#954 Add template_level_volume example
  docs/examples/workflows/template_level_volume.md
  docs/examples/workflows/use-cases/fine_tune_llama.md
  examples/workflows/template-level-volume.yaml
  examples/workflows/template_level_volume.py
  examples/workflows/use_cases/fine-tune-llama.yaml
Labels: semver:patch, type:documentation

#938 Add RunnerInput/Output Pydantic V2 classes
  src/hera/shared/_pydantic.py
  src/hera/workflows/__init__.py
  src/hera/workflows/io/__init__.py
  src/hera/workflows/io/v1.py
  src/hera/workflows/io/v2.py
  src/hera/workflows/runner.py
  src/hera/workflows/script.py
  tests/script_annotations/pydantic_duplicate_input_artifact_names.py
  tests/script_annotations/pydantic_io_invalid_multiple_inputs.py
  tests/script_annotations/pydantic_io_invalid_outputs.py
  tests/script_annotations/pydantic_io_v1.py
  tests/script_annotations/pydantic_io_v2.py
  tests/script_runner/pydantic_io_v1.py
  tests/script_runner/pydantic_io_v2.py
  tests/test_runner.py
  tests/test_script_annotations.py
Labels: type:enhancement, semver:minor

#963 fix(UserContainer): Fix a small bug in ImagePullPolicy mapper and add tests for error cases
  src/hera/workflows/user_container.py
  tests/test_unit/test_user_container.py
Labels: semver:patch, type:bug

#964 Update README.md
  CONTRIBUTING.md
  README.md
Labels: type:skip-changelog

#970 Cleanup pyproject.toml for PyPi
  pyproject.toml
Labels: type:skip-changelog
