Repository argoproj-labs/hera, pull requests merged in 2024-04, with the labels that each got.

#983 New contributor guide
  CONTRIBUTING.md
  README.md
Labels: semver:patch, type:documentation

#1027 Add upper bound for pydantic 1 tests in CI
  .github/workflows/cicd.yaml
Labels: type:skip-changelog

#1026 Add "patches" group to dependabot to use one PR
  .github/dependabot.yml
Labels: type:skip-changelog

#1028 Dedent dependabot labels
  .github/dependabot.yml
Labels: type:skip-changelog

#1029 Update dependencies
  poetry.lock
Labels: semver:patch, type:dependency-upgrade

#1031 Add a hera proposal process
  hep/README.md
  hep/proposals/0000-template.md
Labels: semver:patch, type:documentation

#1018 Fix script-decorated-function typing
  src/hera/workflows/script.py
Labels: semver:patch, type:bug

#1036 Add talk link to tutorial, reorder presentations
  README.md
  docs/walk-through/hera-tour.md
Labels: type:skip-changelog

#994 Upgrade Argo Workflow to 3.5.5
  Makefile
  src/hera/events/models/__init__.py
  src/hera/events/models/eventsource.py
  src/hera/events/models/google/__init__.py
  src/hera/events/models/google/protobuf.py
  src/hera/events/models/grpc/gateway/__init__.py
  src/hera/events/models/grpc/gateway/runtime.py
  src/hera/events/models/io/argoproj/events/__init__.py
  src/hera/events/models/io/argoproj/events/v1alpha1.py
  src/hera/events/models/io/argoproj/workflow/__init__.py
  src/hera/events/models/io/argoproj/workflow/v1alpha1.py
  src/hera/events/models/io/k8s/api/core/__init__.py
  src/hera/events/models/io/k8s/api/core/v1.py
  src/hera/events/models/io/k8s/api/policy/__init__.py
  src/hera/events/models/io/k8s/api/policy/v1.py
  src/hera/events/models/io/k8s/apimachinery/pkg/api/__init__.py
  src/hera/events/models/io/k8s/apimachinery/pkg/api/resource.py
  src/hera/events/models/io/k8s/apimachinery/pkg/apis/meta/__init__.py
  src/hera/events/models/io/k8s/apimachinery/pkg/apis/meta/v1.py
  src/hera/events/models/io/k8s/apimachinery/pkg/util/__init__.py
  src/hera/events/models/io/k8s/apimachinery/pkg/util/intstr.py
  src/hera/events/models/sensor.py
  src/hera/workflows/models/__init__.py
  src/hera/workflows/models/eventsource.py
  src/hera/workflows/models/google/__init__.py
  src/hera/workflows/models/google/protobuf.py
  src/hera/workflows/models/grpc/gateway/__init__.py
  src/hera/workflows/models/grpc/gateway/runtime.py
  src/hera/workflows/models/io/argoproj/events/__init__.py
  src/hera/workflows/models/io/argoproj/events/v1alpha1.py
  src/hera/workflows/models/io/argoproj/workflow/__init__.py
  src/hera/workflows/models/io/argoproj/workflow/v1alpha1.py
  src/hera/workflows/models/io/k8s/api/core/__init__.py
  src/hera/workflows/models/io/k8s/api/core/v1.py
  src/hera/workflows/models/io/k8s/api/policy/__init__.py
  src/hera/workflows/models/io/k8s/api/policy/v1.py
  src/hera/workflows/models/io/k8s/apimachinery/pkg/api/__init__.py
  src/hera/workflows/models/io/k8s/apimachinery/pkg/api/resource.py
  src/hera/workflows/models/io/k8s/apimachinery/pkg/apis/meta/__init__.py
  src/hera/workflows/models/io/k8s/apimachinery/pkg/apis/meta/v1.py
  src/hera/workflows/models/io/k8s/apimachinery/pkg/util/__init__.py
  src/hera/workflows/models/io/k8s/apimachinery/pkg/util/intstr.py
  src/hera/workflows/models/sensor.py
  src/hera/workflows/service.py
Labels: type:dependency-upgrade, semver:minor

#1033 HEP-0001: Add new decorator syntax
  hep/proposals/0000-template.md
  hep/proposals/0001-decorators.md
Labels: type:skip-changelog, final comment period

#1039 enable CronWorkflow.from_dict() to work with subclasses
  src/hera/workflows/cron_workflow.py
Labels: semver:patch, type:bug

#1046 Rename top level `hep` folder to `proposals`
  proposals/README.md
  proposals/heps/0000-template.md
  proposals/heps/0001-decorators.md
Labels: type:skip-changelog

#1047 Refactor mixins
  src/hera/workflows/_meta_mixins.py
  src/hera/workflows/_mixins.py
  src/hera/workflows/container.py
  src/hera/workflows/container_set.py
  src/hera/workflows/cron_workflow.py
  src/hera/workflows/dag.py
  src/hera/workflows/data.py
  src/hera/workflows/http_template.py
  src/hera/workflows/resource.py
  src/hera/workflows/script.py
  src/hera/workflows/steps.py
  src/hera/workflows/suspend.py
  src/hera/workflows/workflow.py
  src/hera/workflows/workflow_template.py
Labels: type:skip-changelog

#1049 Check pydantic.VERSION in place of find_spec
  .github/workflows/cicd.yaml
  src/hera/shared/_pydantic.py
  src/hera/shared/serialization.py
  src/hera/workflows/_runner/util.py
  src/hera/workflows/io/__init__.py
  src/hera/workflows/io/v2.py
Labels: semver:patch, type:bug

#1041 New script decorator
  Makefile
  docs/examples/workflows/experimental/new_decorators_basic_script.md
  examples/workflows/experimental/new-decorators-basic-script.yaml
  examples/workflows/experimental/new_decorators_basic_script.py
  src/hera/shared/_global_config.py
  src/hera/workflows/_meta_mixins.py
  src/hera/workflows/_mixins.py
  src/hera/workflows/container_set.py
  src/hera/workflows/dag.py
  src/hera/workflows/steps.py
  src/hera/workflows/workflow.py
  tests/test_decorators.py
  tests/workflow_decorators/multiple_entrypoints.py
  tests/workflow_decorators/set_entrypoint.py
Labels: type:enhancement, semver:minor

#1052 Remove ArgumentsMixin from wrong classes
  docs/examples/workflows/loops/dynamic_fanout_container.md
  examples/workflows/loops/dynamic_fanout_container.py
  src/hera/workflows/_meta_mixins.py
  src/hera/workflows/_mixins.py
  src/hera/workflows/container.py
  src/hera/workflows/container_set.py
  src/hera/workflows/dag.py
  src/hera/workflows/data.py
  src/hera/workflows/http_template.py
  src/hera/workflows/resource.py
  src/hera/workflows/script.py
  src/hera/workflows/suspend.py
Labels: type:bug, semver:minor
