Repository argoproj-labs/hera, pull requests merged in 2024-10, with the labels that each got.

#1224 Fix TypeError in script.py for functions returning non-types
  src/hera/workflows/script.py
  tests/test_unit/test_script.py
Labels: semver:patch, type:bug

#1225 Update contributing installation guide
  CONTRIBUTING.md
  Makefile
Labels: semver:patch, type:documentation

#1226 Add Hera data science blog to README
  README.md
Labels: semver:patch, type:documentation

#1227 Fix codecov token for github actions
  .github/workflows/cicd.yaml
Labels: type:skip-changelog

#1232 Add Python 3.13 support
  .github/workflows/cicd.yaml
  poetry.lock
Labels: semver:patch, type:dependency-upgrade

#1244 Fix some argo lint errors in examples folder
  docs/examples/workflows/misc/data.md
  docs/examples/workflows/misc/env.md
  docs/examples/workflows/misc/env_from.md
  docs/examples/workflows/misc/http.md
  docs/examples/workflows/misc/suspend.md
  docs/examples/workflows/scripts/callable_script.md
  docs/examples/workflows/scripts/callable_script_v1.md
  docs/examples/workflows/use-cases/fine_tune_llama.md
  docs/examples/workflows/use-cases/map_reduce.md
  docs/examples/workflows/use-cases/spacy_inference_pipeline.md
  docs/examples/workflows/use-cases/spark.md
  examples/workflows/misc/data.py
  examples/workflows/misc/data.yaml
  examples/workflows/misc/env-from.yaml
  examples/workflows/misc/env.py
  examples/workflows/misc/env.yaml
  examples/workflows/misc/env_from.py
  examples/workflows/misc/http.py
  examples/workflows/misc/http.yaml
  examples/workflows/misc/suspend.py
  examples/workflows/misc/suspend.yaml
  examples/workflows/scripts/callable-script-v1.yaml
  examples/workflows/scripts/callable-script.yaml
  examples/workflows/scripts/callable_script.py
  examples/workflows/scripts/callable_script_v1.py
  examples/workflows/use_cases/fine-tune-llama.yaml
  examples/workflows/use_cases/fine_tune_llama.py
  examples/workflows/use_cases/map-reduce.yaml
  examples/workflows/use_cases/map_reduce.py
  examples/workflows/use_cases/spacy-inference-pipeline.yaml
  examples/workflows/use_cases/spacy_inference_pipeline.py
  examples/workflows/use_cases/spark.py
  examples/workflows/use_cases/spark.yaml
Labels: semver:patch, type:task

#1242 Add missing volume claim to user-container example
  docs/examples/workflows/misc/user_container.md
  examples/workflows/misc/user-container.yaml
  examples/workflows/misc/user_container.py
Labels: semver:patch, type:task

#1239 Fix deserialization for str unions
  src/hera/shared/_type_util.py
  src/hera/workflows/_runner/script_annotations_util.py
  src/hera/workflows/_runner/util.py
  src/hera/workflows/script.py
  tests/script_runner/parameter_inputs.py
  tests/test_runner.py
  tests/test_unit/test_shared_type_utils.py
Labels: semver:patch, type:bug

#1236 Fix issues with with_param
  src/hera/shared/_type_util.py
  src/hera/workflows/_meta_mixins.py
  src/hera/workflows/_mixins.py
  src/hera/workflows/io/_io_mixins.py
  src/hera/workflows/script.py
  tests/script_annotations/pydantic_io_with_param.py
  tests/script_annotations/with_param.py
  tests/test_script_annotations.py
  tests/test_unit/test_meta_mixins.py
  tests/test_unit/test_shared_type_utils.py
Labels: semver:patch, type:bug
