Repository argoproj-labs/hera, pull requests merged in 2024-07, with the labels that each got.

#1117 fix: Update script to explicitly reexport models.
  pyproject.toml
  scripts/models.py
  src/hera/events/models/__init__.py
  src/hera/workflows/models/__init__.py
Labels: semver:patch, type:bug

#1124 chore: Add --version to CLI.
  src/hera/__main__.py
Labels: type:enhancement, semver:minor

#1125 Remove anti-pattern script example
  docs/examples/workflows/dags/dag_diamond_with_callable_decorators.md
  docs/examples/workflows/dags/dag_diamond_with_callable_script.md
  docs/examples/workflows/misc/suspend_input_duration.md
  examples/workflows/dags/dag-diamond-with-callable-decorators.yaml
  examples/workflows/dags/dag-diamond-with-callable-script.yaml
  examples/workflows/dags/dag_diamond_with_callable_decorators.py
  examples/workflows/dags/dag_diamond_with_callable_script.py
  examples/workflows/misc/suspend-input-duration.yaml
Labels: type:skip-changelog

#1122 Add Hera logo to README
  README.md
  docs/README.md
  docs/assets/hera-logo.svg
  mkdocs.yml
Labels: type:skip-changelog

#1130 Add favicon for website, fix links
  docs/assets/favicon.ico
  docs/examples/about-upstream.md
  docs/walk-through/advanced-workflow-features.md
  mkdocs.yml
Labels: type:skip-changelog

#1135 Add Alice as a member
  MEMBERS.md
Labels: type:skip-changelog

#1136 Add @jeongukjae as member
  MEMBERS.md
Labels: type:skip-changelog

#1137 Add docs signposts to install `experimental` extra for decorators
  README.md
  docs/README.md
  docs/user-guides/decorators.md
  docs/walk-through/advanced-hera-features.md
Labels: semver:patch, type:documentation

#1143 Add site_url in mkdocs.yml for broken stylesheet links in 404 page
  mkdocs.yml
Labels: semver:patch, type:documentation
