Repository argoproj-labs/hera, pull requests merged in 2024-08, with the labels that each got.

#1153 Disable template name conflict detection
  examples/workflows/steps/recursive-steps.yaml
  examples/workflows/steps/recursive_steps.py
  src/hera/workflows/_context.py
  src/hera/workflows/exceptions.py
  tests/test_unit/test_context.py
Labels: semver:patch, type:bug

#1154 Add missing MD for recursive workflow example
  docs/examples/workflows/steps/recursive_steps.md
Labels: semver:patch, type:documentation

#1157 Refactor init_containers building logic in TemplateMixin
  docs/examples/workflows/misc/init_containers_with_env.md
  examples/workflows/misc/init-containers-with-env.yaml
  examples/workflows/misc/init_containers_with_env.py
  src/hera/workflows/_mixins.py
  src/hera/workflows/container.py
  src/hera/workflows/container_set.py
  src/hera/workflows/dag.py
  src/hera/workflows/data.py
  src/hera/workflows/http_template.py
  src/hera/workflows/resource.py
  src/hera/workflows/script.py
  src/hera/workflows/steps.py
  src/hera/workflows/suspend.py
Labels: semver:patch, type:bug

#1160 Update script to handle Optional and Union input parameters
  Makefile
  src/hera/workflows/_runner/util.py
  src/hera/workflows/script.py
  tests/script_runner/parameter_with_complex_types.py
  tests/submissions/__init__.py
  tests/submissions/test_hello_world.py
  tests/submissions/test_optional_input_parameter.py
  tests/test_runner.py
  tests/test_unit/test_script.py
Labels: semver:patch, type:bug

#1176 Add signpost to existing issues in bug report template
  .github/ISSUE_TEMPLATE/🐛-bug-report.md
Labels: type:skip-changelog

#1178 Fix new container decorator example
  docs/examples/workflows/experimental/new_container_decorator.md
  docs/examples/workflows/misc/init_containers_with_env.md
  examples/workflows/experimental/new-container-decorator.yaml
  examples/workflows/experimental/new_container_decorator.py
  examples/workflows/misc/init-containers-with-env.yaml
  examples/workflows/upstream/work-avoidance.upstream.yaml
Labels: semver:patch, type:documentation

#1179 Add docstrings for ArtifactLoader values
  src/hera/workflows/artifact.py
Labels: semver:patch, type:documentation

#1180 Use overloads in script decorator types
  pyproject.toml
  src/hera/workflows/script.py
  tests/typehints/test-mypy.toml
  tests/typehints/test_script_decorator.py
Labels: semver:patch, type:bug

#1181 Prefer user signature over Hera-added overloads in @script typing
  src/hera/workflows/script.py
  tests/typehints/test_script_decorator.py
Labels: semver:patch, type:enhancement
