Repository argoproj-labs/hera, pull requests merged in 2024-05, with the labels that each got.

#1058 fix boolean in docstring for poll_interval on Workflow.create
  src/hera/workflows/workflow.py
Labels: semver:patch, type:documentation

#1053 Support user specified Bearer tokens
  scripts/service.py
  src/hera/events/service.py
  src/hera/workflows/service.py
  tests/test_workflows_service.py
Labels: type:enhancement, semver:minor

#1060 Refactor RunnerIO classes
  docs/examples/workflows/experimental/new_decorators_basic_script.md
  docs/examples/workflows/experimental/script_runner_io.md
  docs/user-guides/script-runner-io.md
  docs/walk-through/advanced-hera-features.md
  examples/workflows/experimental/new_decorators_basic_script.py
  examples/workflows/experimental/script_runner_io.py
  src/hera/shared/_inspect.py
  src/hera/shared/_pydantic.py
  src/hera/workflows/__init__.py
  src/hera/workflows/_meta_mixins.py
  src/hera/workflows/_runner/script_annotations_util.py
  src/hera/workflows/_runner/util.py
  src/hera/workflows/io/__init__.py
  src/hera/workflows/io/_io_mixins.py
  src/hera/workflows/io/v1.py
  src/hera/workflows/io/v2.py
  src/hera/workflows/script.py
  tests/script_annotations/pydantic_duplicate_input_artifact_names.py
  tests/script_annotations/pydantic_io_invalid_multiple_inputs.py
  tests/script_annotations/pydantic_io_invalid_outputs.py
  tests/script_annotations/pydantic_io_v1.py
  tests/script_annotations/pydantic_io_v1_strs.py
  tests/script_annotations/pydantic_io_v2.py
  tests/script_annotations/pydantic_io_v2_strs.py
  tests/script_runner/pydantic_io_v1.py
  tests/script_runner/pydantic_io_v2.py
  tests/test_runner.py
  tests/test_script_annotations.py
  tests/test_unit/test_script_annotations_util.py
  tests/workflow_decorators/multiple_entrypoints.py
  tests/workflow_decorators/set_entrypoint.py
Labels: type:task, semver:minor

#1066 Propagate WorkflowsService instance from WorkflowTemplate to the created Workflow
  src/hera/workflows/workflow_template.py
  tests/test_unit/test_workflow_template.py
Labels: semver:patch, type:bug

#1067 Add a concrete governance model
  GOVERNANCE.md
  MAINTAINERS.md
  MEMBERS.md
  SECURITY.md
  proposals/README.md
Labels: type:skip-changelog

#1059 New dag decorator
  .github/workflows/cicd.yaml
  Makefile
  docs/examples/workflows/experimental/new_dag_decorator_artifacts.md
  docs/examples/workflows/experimental/new_dag_decorator_inner_dag.md
  docs/examples/workflows/experimental/new_dag_decorator_params.md
  docs/examples/workflows/experimental/new_decorators_basic_script.md
  examples/workflows/experimental/new-dag-decorator-artifacts.yaml
  examples/workflows/experimental/new-dag-decorator-inner-dag.yaml
  examples/workflows/experimental/new-dag-decorator-params.yaml
  examples/workflows/experimental/new_dag_decorator_artifacts.py
  examples/workflows/experimental/new_dag_decorator_inner_dag.py
  examples/workflows/experimental/new_dag_decorator_params.py
  examples/workflows/experimental/new_decorators_basic_script.py
  poetry.lock
  pyproject.toml
  src/hera/shared/_pydantic.py
  src/hera/workflows/_context.py
  src/hera/workflows/_meta_mixins.py
  src/hera/workflows/_mixins.py
  src/hera/workflows/dag.py
  src/hera/workflows/io/_io_mixins.py
  src/hera/workflows/io/v1.py
  tests/test_decorators.py
  tests/workflow_decorators/dag.py
  tests/workflow_decorators/dag_io_declaration.py
  tests/workflow_decorators/dag_io_hoisting.py
  tests/workflow_decorators/dag_io_masked_parameters.py
  tests/workflow_decorators/inner_dag.py
  tests/workflow_decorators/multiple_entrypoints.py
  tests/workflow_decorators/set_entrypoint.py
Labels: type:enhancement, semver:minor

#1062 New steps decorator
  docs/examples/workflows/experimental/new_steps_decorator_with_parallel_steps.md
  examples/workflows/experimental/new-steps-decorator-with-parallel-steps.yaml
  examples/workflows/experimental/new_steps_decorator_with_parallel_steps.py
  src/hera/workflows/__init__.py
  src/hera/workflows/_meta_mixins.py
  src/hera/workflows/steps.py
  tests/test_decorators.py
  tests/workflow_decorators/steps.py
Labels: type:enhancement, semver:minor

#1054 add validation for duplicate template and node names
  src/hera/shared/_pydantic.py
  src/hera/workflows/__init__.py
  src/hera/workflows/_context.py
  src/hera/workflows/dag.py
  src/hera/workflows/exceptions.py
  src/hera/workflows/steps.py
  tests/test_unit/test_context.py
Labels: type:enhancement, semver:minor

#1078 Add superseding flag logic
  docs/examples/workflows/experimental/new_dag_decorator_artifacts.md
  docs/examples/workflows/experimental/new_dag_decorator_inner_dag.md
  docs/examples/workflows/experimental/new_dag_decorator_params.md
  docs/examples/workflows/experimental/new_decorators_basic_script.md
  docs/examples/workflows/experimental/new_steps_decorator_with_parallel_steps.md
  docs/examples/workflows/experimental/script_runner_io.md
  examples/workflows/experimental/new_dag_decorator_artifacts.py
  examples/workflows/experimental/new_dag_decorator_inner_dag.py
  examples/workflows/experimental/new_dag_decorator_params.py
  examples/workflows/experimental/new_decorators_basic_script.py
  examples/workflows/experimental/new_steps_decorator_with_parallel_steps.py
  examples/workflows/experimental/script_runner_io.py
  src/hera/shared/_global_config.py
  src/hera/workflows/_meta_mixins.py
  src/hera/workflows/_mixins.py
  src/hera/workflows/script.py
Labels: type:task, semver:minor

#1077 Add template sets
  docs/examples/workflows/experimental/template_sets.md
  examples/workflows/experimental/template-sets.yaml
  examples/workflows/experimental/template_sets.py
  src/hera/workflows/__init__.py
  src/hera/workflows/template_set.py
  src/hera/workflows/workflow.py
Labels: type:enhancement, semver:minor
