Repository argoproj-labs/hera, pull requests merged in 2024-06, with the labels that each got.

#1082 Add codespace install guide to quick start
  docs/walk-through/quick-start.md
Labels: semver:patch, type:documentation

#1081 Update docs to aid discoverability
  CONTRIBUTING.md
  docs/user-guides/script-basics.md
  docs/walk-through/hello-world.md
  mkdocs.yml
Labels: semver:patch, type:documentation

#1083 Add category for type:informational labels to release drafter
  .github/release-drafter.yml
Labels: type:skip-changelog

#1086 Update pyproject.toml
  pyproject.toml
Labels: type:skip-changelog

#1094 Fix path to misc examples
  mkdocs.yml
Labels: semver:patch, type:documentation

#1087 Add client certificates for workflow service and global. Fixes #1079
  docs/walk-through/authentication.md
  scripts/service.py
  src/hera/events/service.py
  src/hera/shared/_global_config.py
  src/hera/workflows/service.py
  tests/test_workflows_service.py
Labels: type:enhancement, semver:minor

#1093 Support inherited fields for RunnerInput, other niceties
  src/hera/workflows/_runner/script_annotations_util.py
  src/hera/workflows/io/_io_mixins.py
  tests/test_unit/test_io_mixins.py
  tests/test_unit/test_script_annotations_util.py
Labels: semver:patch, type:bug

#1097 Add automatic template ref steps/tasks
  examples/workflows/experimental/new-decorators-auto-template-refs.yaml
  examples/workflows/experimental/new_decorators_auto_template_refs.py
  src/hera/workflows/_meta_mixins.py
Labels: type:enhancement, semver:minor

#1068 New container decorator
  docs/examples/workflows/experimental/new_container_decorator.md
  docs/examples/workflows/experimental/new_decorators_auto_template_refs.md
  examples/workflows/experimental/new-container-decorator.yaml
  examples/workflows/experimental/new-decorators-auto-template-refs.yaml
  examples/workflows/experimental/new_container_decorator.py
  examples/workflows/experimental/new_decorators_auto_template_refs.py
  src/hera/workflows/_meta_mixins.py
  src/hera/workflows/io/_io_mixins.py
  tests/workflow_decorators/container.py
Labels: type:enhancement, semver:minor

#1100 Update template refs example to use different types of templates
  docs/examples/workflows/experimental/new_decorators_auto_template_refs.md
  examples/workflows/experimental/new-decorators-auto-template-refs.yaml
  examples/workflows/experimental/new_decorators_auto_template_refs.py
Labels: semver:patch, type:documentation

#1101 Add decorator syntax guide
  docs/user-guides/decorators.md
  docs/walk-through/advanced-hera-features.md
  mkdocs.yml
Labels: type:documentation, semver:minor

#1104 Add SyntaxError for declaring outside of a Workflow context
  src/hera/workflows/_context.py
  tests/test_async_build.py
  tests/test_unit/test_context.py
Labels: semver:patch, type:enhancement

#1103 Add informational label as one of the minimal type labels
  .github/workflows/minimal-labels.yml
Labels: type:skip-changelog

#1102 Add warning for removal of default in annotated Parameter args
  docs/examples/workflows-examples.md
  docs/examples/workflows/experimental/script_annotations_inputs.md
  examples/workflows/experimental/script_annotations_inputs.py
  examples/workflows/upstream/expression-destructure-json-complex.upstream.yaml
  src/hera/workflows/io/_io_mixins.py
  src/hera/workflows/script.py
  tests/script_annotations_inputs_regression/script_annotations_parameters_combined_new.py
  tests/script_annotations_inputs_regression/script_annotations_parameters_default_both.py
  tests/script_annotations_inputs_regression/script_annotations_parameters_default_new.py
  tests/script_annotations_inputs_regression/script_annotations_parameters_default_old.py
  tests/test_script_annotations.py
Labels: semver:minor, type:informational

#1108 Add IOMixin to Suspend for easier duration configuration
  examples/workflows/misc/suspend_input_duration.py
  src/hera/workflows/suspend.py
Labels: type:enhancement, semver:minor

#1110 Update check-codegen to fail CI if examples not regenerated
  Makefile
  docs/examples/workflows/misc/suspend_input_duration.md
Labels: type:skip-changelog
