Repository argoproj-labs/hera, pull requests merged in 2024-01, with the labels that each got.

#906 feat: Perform dynamic import such that local relative imports functio…
  src/hera/_cli/generate/yaml.py
  tests/cli/examples/relative_imports/file1.py
  tests/cli/examples/relative_imports/file2.py
  tests/cli/test_generate_yaml.py
Labels: semver:patch, type:bug

#918 Fix mypy default args issues in Workflow
  src/hera/workflows/workflow.py
Labels: semver:patch, type:bug

#904 feat: Add --include and --exclude to the hera generate yaml command.
  src/hera/_cli/base.py
  src/hera/_cli/generate/yaml.py
  tests/cli/test_generate_yaml.py
Labels: type:enhancement, semver:minor

#925 Add merge group actions
  .github/workflows/cicd.yaml
  .github/workflows/minimal-labels.yml
Labels: type:skip-changelog

#901 Add new ml pipeline example using spacy in use-cases folder
  docs/examples/workflows/use-cases/spacy_inference_pipeline.md
  examples/workflows/use-cases/spacy-inference-pipeline.yaml
  examples/workflows/use-cases/spacy_inference_pipeline.py
Labels: semver:patch, type:documentation

#931 Fix volume mounts on user container
  docs/examples/workflows/user_container.md
  examples/workflows/upstream/title-and-descriptin-with-markdown.upstream.yaml
  examples/workflows/user-container.yaml
  examples/workflows/user_container.py
  src/hera/workflows/user_container.py
  tests/test_unit/test_user_container.py
Labels: semver:patch, type:bug

#934 Use underscore for examples packages
  docs/generate.py
  examples/workflows/use_cases/__init__.py
  examples/workflows/use_cases/dask.py
  examples/workflows/use_cases/dask.yaml
  examples/workflows/use_cases/map-reduce.yaml
  examples/workflows/use_cases/map_reduce.py
  examples/workflows/use_cases/spacy-inference-pipeline.yaml
  examples/workflows/use_cases/spacy_inference_pipeline.py
  examples/workflows/use_cases/spark.py
  examples/workflows/use_cases/spark.yaml
  examples/workflows/use_cases/workflow-of-workflows.yaml
  examples/workflows/use_cases/workflow_of_workflows.py
Labels: type:skip-changelog

#933 Add brief CLI doc to README
  README.md
Labels: semver:patch, type:documentation

#932 Add example with Weights and Biases + distributed finetuning
  README.md
  docs/examples/workflows/use-cases/fine_tune_llama.md
  docs/examples/workflows/use-cases/wandb_ml_monitoring.md
  examples/workflows/use_cases/fine-tune-llama.yaml
  examples/workflows/use_cases/fine_tune_llama.py
  examples/workflows/use_cases/wandb-ml-monitoring.yaml
  examples/workflows/use_cases/wandb_ml_monitoring.py
Labels: semver:patch, type:documentation

#936 Switch license to Apache 2.0
  LICENSE
Labels: type:skip-changelog

#920 Add Pydantic V1 IO models for use with Hera Runner
  docs/examples/workflows/experimental/script_pydantic_io.md
  examples/workflows/experimental/script-pydantic-io.yaml
  examples/workflows/experimental/script_pydantic_io.py
  src/hera/workflows/io.py
  src/hera/workflows/runner.py
  src/hera/workflows/script.py
  tests/script_annotations/duplicate_input_names.py
  tests/script_annotations/pydantic_duplicate_input_artifact_names.py
  tests/script_annotations/pydantic_io.py
  tests/script_annotations/pydantic_io_invalid_multiple_inputs.py
  tests/script_annotations/pydantic_io_invalid_outputs.py
  tests/script_runner/pydantic_io.py
  tests/test_runner.py
  tests/test_script_annotations.py
Labels: type:enhancement, semver:minor
