Repository argoproj-labs/hera, pull requests merged in 2025-05, with the labels that each got.

#1379 Resolve deprecation warnings of regex library
  docs/generate.py
Labels: type:skip-changelog

#1380 Run `poetry update`
  poetry.lock
Labels: semver:patch, type:dependency-upgrade

#1367 Add custom Artifact serialisation
  src/hera/shared/_global_config.py
  src/hera/workflows/_runner/script_annotations_util.py
  src/hera/workflows/_runner/util.py
  src/hera/workflows/artifact.py
  tests/script_runner/artifact_serialisers_v1.py
  tests/script_runner/artifact_serialisers_v2.py
  tests/test_runner.py
  tests/test_serialisers.py
  tests/test_unit/test_script_annotations_util.py
Labels: type:enhancement, semver:minor

#1368 Add custom serialisation sections to script annotations guide
  docs/user-guides/script-annotations.md
  tests/test_runner.py
Labels: semver:patch, type:documentation

#1374 YAML code converter HEP
  proposals/heps/0002-YAML-converter.md
Labels: semver:patch, type:documentation

#1383 Streamline quick start guide
  CONTRIBUTING.md
  docs/walk-through/quick-start.md
Labels: semver:patch, type:documentation

#1392 Use a `readiness_probe` on daemon example
  docs/examples/workflows/misc/daemon.md
  examples/workflows/misc/daemon.py
  examples/workflows/misc/daemon.yaml
Labels: semver:patch, type:documentation

#1386 Revamp walkthrough (roughly halfway)
  docs/user-guides/core-concepts.md
  docs/user-guides/hera-tutorial.md
  docs/walk-through/about-hera.md
  docs/walk-through/dag.md
  docs/walk-through/dags.md
  docs/walk-through/hello-world.md
  docs/walk-through/parameters.md
  docs/walk-through/script-templates.md
  docs/walk-through/steps.md
  mkdocs.yml
Labels: semver:patch, type:documentation

#1394 Fetch new upstream examples
  docs/examples/workflows-examples.md
  examples/workflows/upstream/dag-daemon-retry-strategy.upstream.yaml
  examples/workflows/upstream/steps-daemon-retry-strategy.upstream.yaml
  examples/workflows/upstream/synchronization-db-mutex-tmpl-level.upstream.yaml
  examples/workflows/upstream/synchronization-db-mutex-wf-level.upstream.yaml
  examples/workflows/upstream/synchronization-db-tmpl-level.upstream.yaml
  examples/workflows/upstream/synchronization-db-wf-level.upstream.yaml
  tests/test_remaining_examples.py
Labels: type:skip-changelog
