Repository argoproj-labs/hera, pull requests merged in 2025-03, with the labels that each got.

#1322 Allow Artifacts in argument dictionaries
  src/hera/workflows/_mixins.py
  tests/test_unit/test_arguments.py
Labels: type:enhancement, semver:minor

#1323 Allow Parameter defaults in WorkflowTemplate arguments
  src/hera/workflows/_mixins.py
  tests/test_unit/test_workflow.py
  tests/test_unit/test_workflow_template.py
Labels: semver:patch, type:bug

#1334 Regenerate test data
  docs/examples/workflows/loops/script_basic_loop.md
  examples/workflows/loops/script-basic-loop.yaml
Labels: type:skip-changelog

#1337 Fix edge case for model parameter conversion
  src/hera/workflows/_mixins.py
  tests/test_unit/test_mixins.py
  tests/test_unit/test_pydantic_io_mixins.py
Labels: semver:patch, type:bug

#1336 Fix `from_model` method in `Parameter` class
  src/hera/workflows/parameter.py
  tests/test_unit/test_workflow_template.py
Labels: semver:patch, type:bug

#1343 Create new docs homepage
  README.md
  docs/README.md
  docs/examples/workflows-examples.md
  docs/index.md
  docs/user-guides/core-concepts.md
  docs/walk-through/about-hera.md
  docs/walk-through/authentication.md
  docs/walk-through/dag.md
  docs/walk-through/template-features.md
  docs/walk-through/workflow-features.md
  mkdocs.yml
Labels: semver:patch, type:documentation

#1339 Refactor runner utils for clarity
  src/hera/workflows/_runner/script_annotations_util.py
  src/hera/workflows/_runner/util.py
  tests/test_runner.py
  tests/test_unit/test_script_annotations_util.py
Labels: semver:patch, type:task

#1351 Add a recursive dag example
  docs/examples/workflows/dags/recursive_dag.md
  examples/workflows/dags/recursive-dag.yaml
  examples/workflows/dags/recursive_dag.py
Labels: semver:patch, type:documentation
