Repository argoproj-labs/hera, pull requests merged in 2025-07, with the labels that each got.

#1431 Add a parquet/pandas example
  docs/examples/workflows/use-cases/parquet_pandas.md
  examples/workflows/use_cases/parquet-pandas.yaml
  examples/workflows/use_cases/parquet_pandas.py
  mkdocs.yml
  tests/test_examples.py
Labels: semver:patch, type:documentation

#1434 Bump pydantic minimum version to v1.10.15
  poetry.lock
  pyproject.toml
Labels: semver:minor, type:informational

#1441 Set Artifact `name` to `None` by default
  src/hera/workflows/artifact.py
Labels: semver:patch, type:bug

#1445 Fix module for script runners generated by CLI and from `__main__`
  src/hera/_cli/generate/__init__.py
  src/hera/_cli/generate/yaml.py
  src/hera/workflows/_runner/util.py
  src/hera/workflows/script.py
  tests/cli/examples/runner_workflow.py
  tests/cli/test_generate_yaml.py
  tests/test_runner.py
  tests/test_unit/test_script.py
Labels: semver:patch, type:bug

#1455 Add Hera `RetryStrategy` to `TemplateMixin` and `Workflow`
  docs/examples/workflows/misc/retry_workflow.md
  examples/workflows/misc/retry-workflow.yaml
  examples/workflows/misc/retry_workflow.py
  src/hera/workflows/_mixins.py
  src/hera/workflows/container.py
  src/hera/workflows/container_set.py
  src/hera/workflows/dag.py
  src/hera/workflows/data.py
  src/hera/workflows/http_template.py
  src/hera/workflows/resource.py
  src/hera/workflows/script.py
  src/hera/workflows/steps.py
  src/hera/workflows/suspend.py
  src/hera/workflows/workflow.py
  tests/test_unit/test_mixins.py
Labels: semver:patch, type:bug
